// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AuthorisedReps generated by hbm2java
 */
@Entity
@Table(name = "authorisedReps", catalog = "turf201_disciplinaries")
public class AuthorisedReps implements java.io.Serializable {

	private Integer id;
	private String repName;
	private String trainerName;
	private String trainerFname;
	private String trainerSname;
	private String trainerAccNo;

	public AuthorisedReps() {
	}

	public AuthorisedReps(String trainerFname, String trainerSname,
			String trainerAccNo) {
		this.trainerFname = trainerFname;
		this.trainerSname = trainerSname;
		this.trainerAccNo = trainerAccNo;
	}

	public AuthorisedReps(String repName, String trainerName,
			String trainerFname, String trainerSname, String trainerAccNo) {
		this.repName = repName;
		this.trainerName = trainerName;
		this.trainerFname = trainerFname;
		this.trainerSname = trainerSname;
		this.trainerAccNo = trainerAccNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "RepName", length = 100)
	public String getRepName() {
		return this.repName;
	}

	public void setRepName(String repName) {
		this.repName = repName;
	}

	@Column(name = "TrainerName", length = 100)
	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	@Column(name = "trainerFName", nullable = false, length = 60)
	public String getTrainerFname() {
		return this.trainerFname;
	}

	public void setTrainerFname(String trainerFname) {
		this.trainerFname = trainerFname;
	}

	@Column(name = "trainerSName", nullable = false, length = 60)
	public String getTrainerSname() {
		return this.trainerSname;
	}

	public void setTrainerSname(String trainerSname) {
		this.trainerSname = trainerSname;
	}

	@Column(name = "trainer_acc_no", nullable = false, length = 20)
	public String getTrainerAccNo() {
		return this.trainerAccNo;
	}

	public void setTrainerAccNo(String trainerAccNo) {
		this.trainerAccNo = trainerAccNo;
	}

}
