// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DisEnquiriesTable generated by hbm2java
 */
@Entity
@Table(name = "dis_enquiries_table", catalog = "turf201_disciplinaries")
public class DisEnquiriesTable implements java.io.Serializable {

	private Integer recEnqId;
	private int recPersonId;
	private int recStatusId;
	private int recRaceTypeId;
	private Date recDate;
	private Integer recRaceNo;
	private int recVenueId;
	private int recSubCatId;
	private String recSummary;
	private String recFullOffence;
	private Integer recFine;
	private boolean recDisciplinary;
	private boolean recAppeal;
	private boolean recReferral;
	private boolean recExplainationNoted;
	private boolean recPointToPoint;
	private String recHorseName;
	private Date recEnteredDate;
	private int recVersionNo;
	private String recEnteredBy;
	private String recComment;
	private int recEnquiryId;
	private int recDaysSuspended;
	private Integer recOnAppealId;
	private Integer recOnReferralId;
	private boolean recAccountsProcessed;

	public DisEnquiriesTable() {
	}

	public DisEnquiriesTable(int recPersonId, int recStatusId,
			int recRaceTypeId, Date recDate, int recVenueId, int recSubCatId,
			String recSummary, boolean recDisciplinary, boolean recAppeal,
			boolean recReferral, boolean recExplainationNoted,
			boolean recPointToPoint, Date recEnteredDate, int recVersionNo,
			int recEnquiryId, int recDaysSuspended, boolean recAccountsProcessed) {
		this.recPersonId = recPersonId;
		this.recStatusId = recStatusId;
		this.recRaceTypeId = recRaceTypeId;
		this.recDate = recDate;
		this.recVenueId = recVenueId;
		this.recSubCatId = recSubCatId;
		this.recSummary = recSummary;
		this.recDisciplinary = recDisciplinary;
		this.recAppeal = recAppeal;
		this.recReferral = recReferral;
		this.recExplainationNoted = recExplainationNoted;
		this.recPointToPoint = recPointToPoint;
		this.recEnteredDate = recEnteredDate;
		this.recVersionNo = recVersionNo;
		this.recEnquiryId = recEnquiryId;
		this.recDaysSuspended = recDaysSuspended;
		this.recAccountsProcessed = recAccountsProcessed;
	}

	public DisEnquiriesTable(int recPersonId, int recStatusId,
			int recRaceTypeId, Date recDate, Integer recRaceNo, int recVenueId,
			int recSubCatId, String recSummary, String recFullOffence,
			Integer recFine, boolean recDisciplinary, boolean recAppeal,
			boolean recReferral, boolean recExplainationNoted,
			boolean recPointToPoint, String recHorseName, Date recEnteredDate,
			int recVersionNo, String recEnteredBy, String recComment,
			int recEnquiryId, int recDaysSuspended, Integer recOnAppealId,
			Integer recOnReferralId, boolean recAccountsProcessed) {
		this.recPersonId = recPersonId;
		this.recStatusId = recStatusId;
		this.recRaceTypeId = recRaceTypeId;
		this.recDate = recDate;
		this.recRaceNo = recRaceNo;
		this.recVenueId = recVenueId;
		this.recSubCatId = recSubCatId;
		this.recSummary = recSummary;
		this.recFullOffence = recFullOffence;
		this.recFine = recFine;
		this.recDisciplinary = recDisciplinary;
		this.recAppeal = recAppeal;
		this.recReferral = recReferral;
		this.recExplainationNoted = recExplainationNoted;
		this.recPointToPoint = recPointToPoint;
		this.recHorseName = recHorseName;
		this.recEnteredDate = recEnteredDate;
		this.recVersionNo = recVersionNo;
		this.recEnteredBy = recEnteredBy;
		this.recComment = recComment;
		this.recEnquiryId = recEnquiryId;
		this.recDaysSuspended = recDaysSuspended;
		this.recOnAppealId = recOnAppealId;
		this.recOnReferralId = recOnReferralId;
		this.recAccountsProcessed = recAccountsProcessed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rec_enq_id", unique = true, nullable = false)
	public Integer getRecEnqId() {
		return this.recEnqId;
	}

	public void setRecEnqId(Integer recEnqId) {
		this.recEnqId = recEnqId;
	}

	@Column(name = "rec_person_id", nullable = false)
	public int getRecPersonId() {
		return this.recPersonId;
	}

	public void setRecPersonId(int recPersonId) {
		this.recPersonId = recPersonId;
	}

	@Column(name = "rec_status_id", nullable = false)
	public int getRecStatusId() {
		return this.recStatusId;
	}

	public void setRecStatusId(int recStatusId) {
		this.recStatusId = recStatusId;
	}

	@Column(name = "rec_race_type_id", nullable = false)
	public int getRecRaceTypeId() {
		return this.recRaceTypeId;
	}

	public void setRecRaceTypeId(int recRaceTypeId) {
		this.recRaceTypeId = recRaceTypeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rec_date", nullable = false, length = 10)
	public Date getRecDate() {
		return this.recDate;
	}

	public void setRecDate(Date recDate) {
		this.recDate = recDate;
	}

	@Column(name = "rec_race_no")
	public Integer getRecRaceNo() {
		return this.recRaceNo;
	}

	public void setRecRaceNo(Integer recRaceNo) {
		this.recRaceNo = recRaceNo;
	}

	@Column(name = "rec_venue_id", nullable = false)
	public int getRecVenueId() {
		return this.recVenueId;
	}

	public void setRecVenueId(int recVenueId) {
		this.recVenueId = recVenueId;
	}

	@Column(name = "rec_sub_cat_id", nullable = false)
	public int getRecSubCatId() {
		return this.recSubCatId;
	}

	public void setRecSubCatId(int recSubCatId) {
		this.recSubCatId = recSubCatId;
	}

	@Column(name = "rec_summary", nullable = false, length = 65535)
	public String getRecSummary() {
		return this.recSummary;
	}

	public void setRecSummary(String recSummary) {
		this.recSummary = recSummary;
	}

	@Column(name = "rec_full_offence")
	public String getRecFullOffence() {
		return this.recFullOffence;
	}

	public void setRecFullOffence(String recFullOffence) {
		this.recFullOffence = recFullOffence;
	}

	@Column(name = "rec_fine")
	public Integer getRecFine() {
		return this.recFine;
	}

	public void setRecFine(Integer recFine) {
		this.recFine = recFine;
	}

	@Column(name = "rec_disciplinary", nullable = false)
	public boolean isRecDisciplinary() {
		return this.recDisciplinary;
	}

	public void setRecDisciplinary(boolean recDisciplinary) {
		this.recDisciplinary = recDisciplinary;
	}

	@Column(name = "rec_appeal", nullable = false)
	public boolean isRecAppeal() {
		return this.recAppeal;
	}

	public void setRecAppeal(boolean recAppeal) {
		this.recAppeal = recAppeal;
	}

	@Column(name = "rec_referral", nullable = false)
	public boolean isRecReferral() {
		return this.recReferral;
	}

	public void setRecReferral(boolean recReferral) {
		this.recReferral = recReferral;
	}

	@Column(name = "rec_explaination_noted", nullable = false)
	public boolean isRecExplainationNoted() {
		return this.recExplainationNoted;
	}

	public void setRecExplainationNoted(boolean recExplainationNoted) {
		this.recExplainationNoted = recExplainationNoted;
	}

	@Column(name = "rec_point_to_point", nullable = false)
	public boolean isRecPointToPoint() {
		return this.recPointToPoint;
	}

	public void setRecPointToPoint(boolean recPointToPoint) {
		this.recPointToPoint = recPointToPoint;
	}

	@Column(name = "rec_horse_name", length = 65535)
	public String getRecHorseName() {
		return this.recHorseName;
	}

	public void setRecHorseName(String recHorseName) {
		this.recHorseName = recHorseName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_entered_date", nullable = false, length = 19)
	public Date getRecEnteredDate() {
		return this.recEnteredDate;
	}

	public void setRecEnteredDate(Date recEnteredDate) {
		this.recEnteredDate = recEnteredDate;
	}

	@Column(name = "rec_version_no", nullable = false)
	public int getRecVersionNo() {
		return this.recVersionNo;
	}

	public void setRecVersionNo(int recVersionNo) {
		this.recVersionNo = recVersionNo;
	}

	@Column(name = "rec_entered_by", length = 50)
	public String getRecEnteredBy() {
		return this.recEnteredBy;
	}

	public void setRecEnteredBy(String recEnteredBy) {
		this.recEnteredBy = recEnteredBy;
	}

	@Column(name = "rec_comment", length = 16777215)
	public String getRecComment() {
		return this.recComment;
	}

	public void setRecComment(String recComment) {
		this.recComment = recComment;
	}

	@Column(name = "rec_enquiry_id", nullable = false)
	public int getRecEnquiryId() {
		return this.recEnquiryId;
	}

	public void setRecEnquiryId(int recEnquiryId) {
		this.recEnquiryId = recEnquiryId;
	}

	@Column(name = "rec_days_suspended", nullable = false)
	public int getRecDaysSuspended() {
		return this.recDaysSuspended;
	}

	public void setRecDaysSuspended(int recDaysSuspended) {
		this.recDaysSuspended = recDaysSuspended;
	}

	@Column(name = "rec_on_appeal_id")
	public Integer getRecOnAppealId() {
		return this.recOnAppealId;
	}

	public void setRecOnAppealId(Integer recOnAppealId) {
		this.recOnAppealId = recOnAppealId;
	}

	@Column(name = "rec_on_referral_id")
	public Integer getRecOnReferralId() {
		return this.recOnReferralId;
	}

	public void setRecOnReferralId(Integer recOnReferralId) {
		this.recOnReferralId = recOnReferralId;
	}

	@Column(name = "rec_accounts_processed", nullable = false)
	public boolean isRecAccountsProcessed() {
		return this.recAccountsProcessed;
	}

	public void setRecAccountsProcessed(boolean recAccountsProcessed) {
		this.recAccountsProcessed = recAccountsProcessed;
	}

}
