// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DisEnquiriesTemplates generated by hbm2java
 */
@Entity
@Table(name = "dis_enquiries_templates", catalog = "turf201_disciplinaries")
public class DisEnquiriesTemplates implements java.io.Serializable {

	private Integer enqTempId;
	private String enqTempName;
	private int enqTempSubCatId;
	private String enqTempTemplate;
	private byte multiple;
	private byte enqHasDiscip;
	private byte enqTempRaceCardFillable;

	public DisEnquiriesTemplates() {
	}

	public DisEnquiriesTemplates(String enqTempName, int enqTempSubCatId,
			String enqTempTemplate, byte multiple, byte enqHasDiscip,
			byte enqTempRaceCardFillable) {
		this.enqTempName = enqTempName;
		this.enqTempSubCatId = enqTempSubCatId;
		this.enqTempTemplate = enqTempTemplate;
		this.multiple = multiple;
		this.enqHasDiscip = enqHasDiscip;
		this.enqTempRaceCardFillable = enqTempRaceCardFillable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "enq_temp_id", unique = true, nullable = false)
	public Integer getEnqTempId() {
		return this.enqTempId;
	}

	public void setEnqTempId(Integer enqTempId) {
		this.enqTempId = enqTempId;
	}

	@Column(name = "enq_temp_name", nullable = false, length = 70)
	public String getEnqTempName() {
		return this.enqTempName;
	}

	public void setEnqTempName(String enqTempName) {
		this.enqTempName = enqTempName;
	}

	@Column(name = "enq_temp_sub_cat_id", nullable = false)
	public int getEnqTempSubCatId() {
		return this.enqTempSubCatId;
	}

	public void setEnqTempSubCatId(int enqTempSubCatId) {
		this.enqTempSubCatId = enqTempSubCatId;
	}

	@Column(name = "enq_temp_template", nullable = false)
	public String getEnqTempTemplate() {
		return this.enqTempTemplate;
	}

	public void setEnqTempTemplate(String enqTempTemplate) {
		this.enqTempTemplate = enqTempTemplate;
	}

	@Column(name = "multiple", nullable = false)
	public byte getMultiple() {
		return this.multiple;
	}

	public void setMultiple(byte multiple) {
		this.multiple = multiple;
	}

	@Column(name = "enq_has_discip", nullable = false)
	public byte getEnqHasDiscip() {
		return this.enqHasDiscip;
	}

	public void setEnqHasDiscip(byte enqHasDiscip) {
		this.enqHasDiscip = enqHasDiscip;
	}

	@Column(name = "enq_temp_race_card_fillable", nullable = false)
	public byte getEnqTempRaceCardFillable() {
		return this.enqTempRaceCardFillable;
	}

	public void setEnqTempRaceCardFillable(byte enqTempRaceCardFillable) {
		this.enqTempRaceCardFillable = enqTempRaceCardFillable;
	}

}
