// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DisEmailPressList generated by hbm2java
 */
@Entity
@Table(name = "dis_email_press_list", catalog = "turf201_disciplinaries")
public class DisEmailPressList implements java.io.Serializable {

	private Integer emailId;
	private String emailAddress;

	public DisEmailPressList() {
	}

	public DisEmailPressList(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "email_id", unique = true, nullable = false)
	public Integer getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Integer emailId) {
		this.emailId = emailId;
	}

	@Column(name = "email_address", nullable = false, length = 200)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

}
