// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DisFromWeb generated by hbm2java
 */
@Entity
@Table(name = "dis_from_web", catalog = "turf201_disciplinaries")
public class DisFromWeb implements java.io.Serializable {

	private Integer webId;
	private int webEnqId;
	private Date webDate;
	private int webVersion;

	public DisFromWeb() {
	}

	public DisFromWeb(int webEnqId, Date webDate, int webVersion) {
		this.webEnqId = webEnqId;
		this.webDate = webDate;
		this.webVersion = webVersion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "web_id", unique = true, nullable = false)
	public Integer getWebId() {
		return this.webId;
	}

	public void setWebId(Integer webId) {
		this.webId = webId;
	}

	@Column(name = "web_enq_id", nullable = false)
	public int getWebEnqId() {
		return this.webEnqId;
	}

	public void setWebEnqId(int webEnqId) {
		this.webEnqId = webEnqId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "web_date", nullable = false, length = 10)
	public Date getWebDate() {
		return this.webDate;
	}

	public void setWebDate(Date webDate) {
		this.webDate = webDate;
	}

	@Column(name = "web_version", nullable = false)
	public int getWebVersion() {
		return this.webVersion;
	}

	public void setWebVersion(int webVersion) {
		this.webVersion = webVersion;
	}

}
