// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DisImportedCalendars generated by hbm2java
 */
@Entity
@Table(name = "dis_imported_calendars", catalog = "turf201_disciplinaries")
public class DisImportedCalendars implements java.io.Serializable {

	private Integer importedCalendarId;
	private String importCalendarFileName;

	public DisImportedCalendars() {
	}

	public DisImportedCalendars(String importCalendarFileName) {
		this.importCalendarFileName = importCalendarFileName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "imported_calendar_id", unique = true, nullable = false)
	public Integer getImportedCalendarId() {
		return this.importedCalendarId;
	}

	public void setImportedCalendarId(Integer importedCalendarId) {
		this.importedCalendarId = importedCalendarId;
	}

	@Column(name = "import_calendar_file_name", nullable = false, length = 150)
	public String getImportCalendarFileName() {
		return this.importCalendarFileName;
	}

	public void setImportCalendarFileName(String importCalendarFileName) {
		this.importCalendarFileName = importCalendarFileName;
	}

}
