// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DisImportedRacecards generated by hbm2java
 */
@Entity
@Table(name = "dis_imported_racecards", catalog = "turf201_disciplinaries")
public class DisImportedRacecards implements java.io.Serializable {

	private Integer impId;
	private String impFilename;
	private Date impDate;

	public DisImportedRacecards() {
	}

	public DisImportedRacecards(String impFilename, Date impDate) {
		this.impFilename = impFilename;
		this.impDate = impDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "imp_id", unique = true, nullable = false)
	public Integer getImpId() {
		return this.impId;
	}

	public void setImpId(Integer impId) {
		this.impId = impId;
	}

	@Column(name = "imp_filename", nullable = false, length = 200)
	public String getImpFilename() {
		return this.impFilename;
	}

	public void setImpFilename(String impFilename) {
		this.impFilename = impFilename;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "imp_date", nullable = false, length = 10)
	public Date getImpDate() {
		return this.impDate;
	}

	public void setImpDate(Date impDate) {
		this.impDate = impDate;
	}

}
