// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DisOnAppeal generated by hbm2java
 */
@Entity
@Table(name = "dis_on_appeal", catalog = "turf201_disciplinaries")
public class DisOnAppeal implements java.io.Serializable {

	private Integer onAppId;
	private int onAppEnqId;
	private Date onAppDate;
	private int onAppVersion;

	public DisOnAppeal() {
	}

	public DisOnAppeal(int onAppEnqId, Date onAppDate, int onAppVersion) {
		this.onAppEnqId = onAppEnqId;
		this.onAppDate = onAppDate;
		this.onAppVersion = onAppVersion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "on_app_id", unique = true, nullable = false)
	public Integer getOnAppId() {
		return this.onAppId;
	}

	public void setOnAppId(Integer onAppId) {
		this.onAppId = onAppId;
	}

	@Column(name = "on_app_enq_Id", nullable = false)
	public int getOnAppEnqId() {
		return this.onAppEnqId;
	}

	public void setOnAppEnqId(int onAppEnqId) {
		this.onAppEnqId = onAppEnqId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "on_app_date", nullable = false, length = 10)
	public Date getOnAppDate() {
		return this.onAppDate;
	}

	public void setOnAppDate(Date onAppDate) {
		this.onAppDate = onAppDate;
	}

	@Column(name = "on_app_version", nullable = false)
	public int getOnAppVersion() {
		return this.onAppVersion;
	}

	public void setOnAppVersion(int onAppVersion) {
		this.onAppVersion = onAppVersion;
	}

}
