// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DisOnReferral generated by hbm2java
 */
@Entity
@Table(name = "dis_on_referral", catalog = "turf201_disciplinaries")
public class DisOnReferral implements java.io.Serializable {

	private Integer refId;
	private int refEnqId;
	private Date refDate;
	private int refVersion;

	public DisOnReferral() {
	}

	public DisOnReferral(int refEnqId, Date refDate, int refVersion) {
		this.refEnqId = refEnqId;
		this.refDate = refDate;
		this.refVersion = refVersion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ref_id", unique = true, nullable = false)
	public Integer getRefId() {
		return this.refId;
	}

	public void setRefId(Integer refId) {
		this.refId = refId;
	}

	@Column(name = "ref_enq_id", nullable = false)
	public int getRefEnqId() {
		return this.refEnqId;
	}

	public void setRefEnqId(int refEnqId) {
		this.refEnqId = refEnqId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ref_date", nullable = false, length = 10)
	public Date getRefDate() {
		return this.refDate;
	}

	public void setRefDate(Date refDate) {
		this.refDate = refDate;
	}

	@Column(name = "ref_version", nullable = false)
	public int getRefVersion() {
		return this.refVersion;
	}

	public void setRefVersion(int refVersion) {
		this.refVersion = refVersion;
	}

}
