// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DisRaceTypes generated by hbm2java
 */
@Entity
@Table(name = "dis_race_types", catalog = "turf201_disciplinaries")
public class DisRaceTypes implements java.io.Serializable {

	private Integer ractypId;
	private String ractypName;
	private int ractypStatusId;

	public DisRaceTypes() {
	}

	public DisRaceTypes(String ractypName, int ractypStatusId) {
		this.ractypName = ractypName;
		this.ractypStatusId = ractypStatusId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ractyp_id", unique = true, nullable = false)
	public Integer getRactypId() {
		return this.ractypId;
	}

	public void setRactypId(Integer ractypId) {
		this.ractypId = ractypId;
	}

	@Column(name = "ractyp_name", nullable = false, length = 65535)
	public String getRactypName() {
		return this.ractypName;
	}

	public void setRactypName(String ractypName) {
		this.ractypName = ractypName;
	}

	@Column(name = "ractyp_status_id", nullable = false)
	public int getRactypStatusId() {
		return this.ractypStatusId;
	}

	public void setRactypStatusId(int ractypStatusId) {
		this.ractypStatusId = ractypStatusId;
	}

}
