// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DisRacecourseEnquiries generated by hbm2java
 */
@Entity
@Table(name = "dis_racecourse_enquiries", catalog = "turf201_disciplinaries")
public class DisRacecourseEnquiries implements java.io.Serializable {

	private Integer racId;
	private String racPerson;
	private int racStatus;
	private int racRaceType;
	private Date racDate;
	private int racVenue;
	private int racSubCat;
	private String racSummary;
	private String racFine;
	private String racFullOffence;
	private int racVersionNo;
	private String racEnteredBy;
	private Date racLastModified;
	private String racComment;
	private String racHorseName;
	private byte racRaceCard;
	private int racFullEnqId;
	private byte racIsDeleted;
	private String racDiscipType;
	private int racSuspendedDays;

	public DisRacecourseEnquiries() {
	}

	public DisRacecourseEnquiries(String racPerson, int racStatus,
			int racRaceType, Date racDate, int racVenue, int racSubCat,
			String racSummary, int racVersionNo, String racEnteredBy,
			Date racLastModified, byte racRaceCard, int racFullEnqId,
			byte racIsDeleted, String racDiscipType, int racSuspendedDays) {
		this.racPerson = racPerson;
		this.racStatus = racStatus;
		this.racRaceType = racRaceType;
		this.racDate = racDate;
		this.racVenue = racVenue;
		this.racSubCat = racSubCat;
		this.racSummary = racSummary;
		this.racVersionNo = racVersionNo;
		this.racEnteredBy = racEnteredBy;
		this.racLastModified = racLastModified;
		this.racRaceCard = racRaceCard;
		this.racFullEnqId = racFullEnqId;
		this.racIsDeleted = racIsDeleted;
		this.racDiscipType = racDiscipType;
		this.racSuspendedDays = racSuspendedDays;
	}

	public DisRacecourseEnquiries(String racPerson, int racStatus,
			int racRaceType, Date racDate, int racVenue, int racSubCat,
			String racSummary, String racFine, String racFullOffence,
			int racVersionNo, String racEnteredBy, Date racLastModified,
			String racComment, String racHorseName, byte racRaceCard,
			int racFullEnqId, byte racIsDeleted, String racDiscipType,
			int racSuspendedDays) {
		this.racPerson = racPerson;
		this.racStatus = racStatus;
		this.racRaceType = racRaceType;
		this.racDate = racDate;
		this.racVenue = racVenue;
		this.racSubCat = racSubCat;
		this.racSummary = racSummary;
		this.racFine = racFine;
		this.racFullOffence = racFullOffence;
		this.racVersionNo = racVersionNo;
		this.racEnteredBy = racEnteredBy;
		this.racLastModified = racLastModified;
		this.racComment = racComment;
		this.racHorseName = racHorseName;
		this.racRaceCard = racRaceCard;
		this.racFullEnqId = racFullEnqId;
		this.racIsDeleted = racIsDeleted;
		this.racDiscipType = racDiscipType;
		this.racSuspendedDays = racSuspendedDays;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rac_id", unique = true, nullable = false)
	public Integer getRacId() {
		return this.racId;
	}

	public void setRacId(Integer racId) {
		this.racId = racId;
	}

	@Column(name = "rac_person", nullable = false, length = 200)
	public String getRacPerson() {
		return this.racPerson;
	}

	public void setRacPerson(String racPerson) {
		this.racPerson = racPerson;
	}

	@Column(name = "rac_status", nullable = false)
	public int getRacStatus() {
		return this.racStatus;
	}

	public void setRacStatus(int racStatus) {
		this.racStatus = racStatus;
	}

	@Column(name = "rac_race_type", nullable = false)
	public int getRacRaceType() {
		return this.racRaceType;
	}

	public void setRacRaceType(int racRaceType) {
		this.racRaceType = racRaceType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rac_date", nullable = false, length = 10)
	public Date getRacDate() {
		return this.racDate;
	}

	public void setRacDate(Date racDate) {
		this.racDate = racDate;
	}

	@Column(name = "rac_venue", nullable = false)
	public int getRacVenue() {
		return this.racVenue;
	}

	public void setRacVenue(int racVenue) {
		this.racVenue = racVenue;
	}

	@Column(name = "rac_sub_cat", nullable = false)
	public int getRacSubCat() {
		return this.racSubCat;
	}

	public void setRacSubCat(int racSubCat) {
		this.racSubCat = racSubCat;
	}

	@Column(name = "rac_summary", nullable = false)
	public String getRacSummary() {
		return this.racSummary;
	}

	public void setRacSummary(String racSummary) {
		this.racSummary = racSummary;
	}

	@Column(name = "rac_fine", length = 100)
	public String getRacFine() {
		return this.racFine;
	}

	public void setRacFine(String racFine) {
		this.racFine = racFine;
	}

	@Column(name = "rac_full_offence")
	public String getRacFullOffence() {
		return this.racFullOffence;
	}

	public void setRacFullOffence(String racFullOffence) {
		this.racFullOffence = racFullOffence;
	}

	@Column(name = "rac_version_no", nullable = false)
	public int getRacVersionNo() {
		return this.racVersionNo;
	}

	public void setRacVersionNo(int racVersionNo) {
		this.racVersionNo = racVersionNo;
	}

	@Column(name = "rac_entered_by", nullable = false, length = 200)
	public String getRacEnteredBy() {
		return this.racEnteredBy;
	}

	public void setRacEnteredBy(String racEnteredBy) {
		this.racEnteredBy = racEnteredBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rac_last_modified", nullable = false, length = 19)
	public Date getRacLastModified() {
		return this.racLastModified;
	}

	public void setRacLastModified(Date racLastModified) {
		this.racLastModified = racLastModified;
	}

	@Column(name = "rac_comment")
	public String getRacComment() {
		return this.racComment;
	}

	public void setRacComment(String racComment) {
		this.racComment = racComment;
	}

	@Column(name = "rac_horse_name", length = 200)
	public String getRacHorseName() {
		return this.racHorseName;
	}

	public void setRacHorseName(String racHorseName) {
		this.racHorseName = racHorseName;
	}

	@Column(name = "rac_race_card", nullable = false)
	public byte getRacRaceCard() {
		return this.racRaceCard;
	}

	public void setRacRaceCard(byte racRaceCard) {
		this.racRaceCard = racRaceCard;
	}

	@Column(name = "rac_full_enq_id", nullable = false)
	public int getRacFullEnqId() {
		return this.racFullEnqId;
	}

	public void setRacFullEnqId(int racFullEnqId) {
		this.racFullEnqId = racFullEnqId;
	}

	@Column(name = "rac_is_deleted", nullable = false)
	public byte getRacIsDeleted() {
		return this.racIsDeleted;
	}

	public void setRacIsDeleted(byte racIsDeleted) {
		this.racIsDeleted = racIsDeleted;
	}

	@Column(name = "rac_discip_type", nullable = false, length = 200)
	public String getRacDiscipType() {
		return this.racDiscipType;
	}

	public void setRacDiscipType(String racDiscipType) {
		this.racDiscipType = racDiscipType;
	}

	@Column(name = "rac_suspended_days", nullable = false)
	public int getRacSuspendedDays() {
		return this.racSuspendedDays;
	}

	public void setRacSuspendedDays(int racSuspendedDays) {
		this.racSuspendedDays = racSuspendedDays;
	}

}
