// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DisRacecourseFullEnquiries generated by hbm2java
 */
@Entity
@Table(name = "dis_racecourse_full_enquiries", catalog = "turf201_disciplinaries")
public class DisRacecourseFullEnquiries implements java.io.Serializable {

	private Integer enqId;
	private String enqText;
	private String enqMeeting;
	private Date enqDate;
	private String enqEnteredBy;
	private byte enqIsDeleted;
	private String enqRaceCode;
	private String enqRaceName;
	private String enqEnqType;
	private byte enqIsSentToCalendar;
	private byte enqIsUploaded;
	private byte enqShouldHaveDiscip;
	private byte enqIsEmailed;
	private byte enqIsAccepted;
	private byte enqIsTurfclubApproved;

	public DisRacecourseFullEnquiries() {
	}

	public DisRacecourseFullEnquiries(String enqText, String enqMeeting,
			Date enqDate, String enqEnteredBy, byte enqIsDeleted,
			String enqRaceCode, String enqRaceName, String enqEnqType,
			byte enqIsSentToCalendar, byte enqIsUploaded,
			byte enqShouldHaveDiscip, byte enqIsEmailed, byte enqIsAccepted,
			byte enqIsTurfclubApproved) {
		this.enqText = enqText;
		this.enqMeeting = enqMeeting;
		this.enqDate = enqDate;
		this.enqEnteredBy = enqEnteredBy;
		this.enqIsDeleted = enqIsDeleted;
		this.enqRaceCode = enqRaceCode;
		this.enqRaceName = enqRaceName;
		this.enqEnqType = enqEnqType;
		this.enqIsSentToCalendar = enqIsSentToCalendar;
		this.enqIsUploaded = enqIsUploaded;
		this.enqShouldHaveDiscip = enqShouldHaveDiscip;
		this.enqIsEmailed = enqIsEmailed;
		this.enqIsAccepted = enqIsAccepted;
		this.enqIsTurfclubApproved = enqIsTurfclubApproved;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "enq_id", unique = true, nullable = false)
	public Integer getEnqId() {
		return this.enqId;
	}

	public void setEnqId(Integer enqId) {
		this.enqId = enqId;
	}

	@Column(name = "enq_text", nullable = false)
	public String getEnqText() {
		return this.enqText;
	}

	public void setEnqText(String enqText) {
		this.enqText = enqText;
	}

	@Column(name = "enq_meeting", nullable = false, length = 200)
	public String getEnqMeeting() {
		return this.enqMeeting;
	}

	public void setEnqMeeting(String enqMeeting) {
		this.enqMeeting = enqMeeting;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enq_date", nullable = false, length = 10)
	public Date getEnqDate() {
		return this.enqDate;
	}

	public void setEnqDate(Date enqDate) {
		this.enqDate = enqDate;
	}

	@Column(name = "enq_entered_by", nullable = false, length = 30)
	public String getEnqEnteredBy() {
		return this.enqEnteredBy;
	}

	public void setEnqEnteredBy(String enqEnteredBy) {
		this.enqEnteredBy = enqEnteredBy;
	}

	@Column(name = "enq_is_deleted", nullable = false)
	public byte getEnqIsDeleted() {
		return this.enqIsDeleted;
	}

	public void setEnqIsDeleted(byte enqIsDeleted) {
		this.enqIsDeleted = enqIsDeleted;
	}

	@Column(name = "enq_race_code", nullable = false, length = 20)
	public String getEnqRaceCode() {
		return this.enqRaceCode;
	}

	public void setEnqRaceCode(String enqRaceCode) {
		this.enqRaceCode = enqRaceCode;
	}

	@Column(name = "enq_race_name", nullable = false, length = 200)
	public String getEnqRaceName() {
		return this.enqRaceName;
	}

	public void setEnqRaceName(String enqRaceName) {
		this.enqRaceName = enqRaceName;
	}

	@Column(name = "enq_enq_type", nullable = false, length = 16)
	public String getEnqEnqType() {
		return this.enqEnqType;
	}

	public void setEnqEnqType(String enqEnqType) {
		this.enqEnqType = enqEnqType;
	}

	@Column(name = "enq_is_sent_to_calendar", nullable = false)
	public byte getEnqIsSentToCalendar() {
		return this.enqIsSentToCalendar;
	}

	public void setEnqIsSentToCalendar(byte enqIsSentToCalendar) {
		this.enqIsSentToCalendar = enqIsSentToCalendar;
	}

	@Column(name = "enq_is_uploaded", nullable = false)
	public byte getEnqIsUploaded() {
		return this.enqIsUploaded;
	}

	public void setEnqIsUploaded(byte enqIsUploaded) {
		this.enqIsUploaded = enqIsUploaded;
	}

	@Column(name = "enq_should_have_discip", nullable = false)
	public byte getEnqShouldHaveDiscip() {
		return this.enqShouldHaveDiscip;
	}

	public void setEnqShouldHaveDiscip(byte enqShouldHaveDiscip) {
		this.enqShouldHaveDiscip = enqShouldHaveDiscip;
	}

	@Column(name = "enq_is_emailed", nullable = false)
	public byte getEnqIsEmailed() {
		return this.enqIsEmailed;
	}

	public void setEnqIsEmailed(byte enqIsEmailed) {
		this.enqIsEmailed = enqIsEmailed;
	}

	@Column(name = "enq_is_accepted", nullable = false)
	public byte getEnqIsAccepted() {
		return this.enqIsAccepted;
	}

	public void setEnqIsAccepted(byte enqIsAccepted) {
		this.enqIsAccepted = enqIsAccepted;
	}

	@Column(name = "enq_is_turfclub_approved", nullable = false)
	public byte getEnqIsTurfclubApproved() {
		return this.enqIsTurfclubApproved;
	}

	public void setEnqIsTurfclubApproved(byte enqIsTurfclubApproved) {
		this.enqIsTurfclubApproved = enqIsTurfclubApproved;
	}

}
