// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DisRacecourseFullEnquiresLinkedRc generated by hbm2java
 */
@Entity
@Table(name = "dis_racecourse_full_enquires_linked_rc", catalog = "turf201_disciplinaries")
public class DisRacecourseFullEnquiresLinkedRc implements java.io.Serializable {

	private Integer linkedRcId;
	private int linkedRcRacecardId;
	private int linkedRcEnqId;
	private byte linkedRcDiscipComplete;

	public DisRacecourseFullEnquiresLinkedRc() {
	}

	public DisRacecourseFullEnquiresLinkedRc(int linkedRcRacecardId,
			int linkedRcEnqId, byte linkedRcDiscipComplete) {
		this.linkedRcRacecardId = linkedRcRacecardId;
		this.linkedRcEnqId = linkedRcEnqId;
		this.linkedRcDiscipComplete = linkedRcDiscipComplete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "linked_rc_id", unique = true, nullable = false)
	public Integer getLinkedRcId() {
		return this.linkedRcId;
	}

	public void setLinkedRcId(Integer linkedRcId) {
		this.linkedRcId = linkedRcId;
	}

	@Column(name = "linked_rc_racecard_id", nullable = false)
	public int getLinkedRcRacecardId() {
		return this.linkedRcRacecardId;
	}

	public void setLinkedRcRacecardId(int linkedRcRacecardId) {
		this.linkedRcRacecardId = linkedRcRacecardId;
	}

	@Column(name = "linked_rc_enq_id", nullable = false)
	public int getLinkedRcEnqId() {
		return this.linkedRcEnqId;
	}

	public void setLinkedRcEnqId(int linkedRcEnqId) {
		this.linkedRcEnqId = linkedRcEnqId;
	}

	@Column(name = "linked_rc_discip_complete", nullable = false)
	public byte getLinkedRcDiscipComplete() {
		return this.linkedRcDiscipComplete;
	}

	public void setLinkedRcDiscipComplete(byte linkedRcDiscipComplete) {
		this.linkedRcDiscipComplete = linkedRcDiscipComplete;
	}

}
