// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DisRacecourseTypes generated by hbm2java
 */
@Entity
@Table(name = "dis_racecourse_types", catalog = "turf201_disciplinaries")
public class DisRacecourseTypes implements java.io.Serializable {

	private Integer racecourseTypeId;
	private String racecourseTypeName;

	public DisRacecourseTypes() {
	}

	public DisRacecourseTypes(String racecourseTypeName) {
		this.racecourseTypeName = racecourseTypeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "racecourse_type_id", unique = true, nullable = false)
	public Integer getRacecourseTypeId() {
		return this.racecourseTypeId;
	}

	public void setRacecourseTypeId(Integer racecourseTypeId) {
		this.racecourseTypeId = racecourseTypeId;
	}

	@Column(name = "racecourse_type_name", nullable = false, length = 65535)
	public String getRacecourseTypeName() {
		return this.racecourseTypeName;
	}

	public void setRacecourseTypeName(String racecourseTypeName) {
		this.racecourseTypeName = racecourseTypeName;
	}

}
