// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DisRaceCard generated by hbm2java
 */
@Entity
@Table(name = "dis_raceCard", catalog = "turf201_disciplinaries")
public class DisRaceCard implements java.io.Serializable {

	private Integer rowId;
	private String accountNo;
	private String trainerName;
	private String raceNo;
	private String horseName;
	private String riderName;
	private String owner1;
	private String owner2;
	private String owner3;
	private String owner4;
	private Date dateRan;
	private String meeting;
	private Date date;
	private boolean betFairImported;
	private int horseNum;
	private String raceCode;
	private String raceName;
	private String jockeyAccNo;

	public DisRaceCard() {
	}

	public DisRaceCard(String accountNo, String trainerName, String raceNo,
			String horseName, String riderName, String owner1, String owner2,
			String owner3, String owner4, Date dateRan, String meeting,
			Date date, boolean betFairImported, int horseNum) {
		this.accountNo = accountNo;
		this.trainerName = trainerName;
		this.raceNo = raceNo;
		this.horseName = horseName;
		this.riderName = riderName;
		this.owner1 = owner1;
		this.owner2 = owner2;
		this.owner3 = owner3;
		this.owner4 = owner4;
		this.dateRan = dateRan;
		this.meeting = meeting;
		this.date = date;
		this.betFairImported = betFairImported;
		this.horseNum = horseNum;
	}

	public DisRaceCard(String accountNo, String trainerName, String raceNo,
			String horseName, String riderName, String owner1, String owner2,
			String owner3, String owner4, Date dateRan, String meeting,
			Date date, boolean betFairImported, int horseNum, String raceCode,
			String raceName, String jockeyAccNo) {
		this.accountNo = accountNo;
		this.trainerName = trainerName;
		this.raceNo = raceNo;
		this.horseName = horseName;
		this.riderName = riderName;
		this.owner1 = owner1;
		this.owner2 = owner2;
		this.owner3 = owner3;
		this.owner4 = owner4;
		this.dateRan = dateRan;
		this.meeting = meeting;
		this.date = date;
		this.betFairImported = betFairImported;
		this.horseNum = horseNum;
		this.raceCode = raceCode;
		this.raceName = raceName;
		this.jockeyAccNo = jockeyAccNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "Account_No", nullable = false, length = 10)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "Trainer_Name", nullable = false, length = 50)
	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	@Column(name = "Race_No", nullable = false, length = 50)
	public String getRaceNo() {
		return this.raceNo;
	}

	public void setRaceNo(String raceNo) {
		this.raceNo = raceNo;
	}

	@Column(name = "Horse_Name", nullable = false, length = 50)
	public String getHorseName() {
		return this.horseName;
	}

	public void setHorseName(String horseName) {
		this.horseName = horseName;
	}

	@Column(name = "Rider_Name", nullable = false, length = 50)
	public String getRiderName() {
		return this.riderName;
	}

	public void setRiderName(String riderName) {
		this.riderName = riderName;
	}

	@Column(name = "Owner1", nullable = false, length = 50)
	public String getOwner1() {
		return this.owner1;
	}

	public void setOwner1(String owner1) {
		this.owner1 = owner1;
	}

	@Column(name = "Owner2", nullable = false, length = 50)
	public String getOwner2() {
		return this.owner2;
	}

	public void setOwner2(String owner2) {
		this.owner2 = owner2;
	}

	@Column(name = "Owner3", nullable = false, length = 50)
	public String getOwner3() {
		return this.owner3;
	}

	public void setOwner3(String owner3) {
		this.owner3 = owner3;
	}

	@Column(name = "Owner4", nullable = false, length = 50)
	public String getOwner4() {
		return this.owner4;
	}

	public void setOwner4(String owner4) {
		this.owner4 = owner4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateRan", nullable = false, length = 10)
	public Date getDateRan() {
		return this.dateRan;
	}

	public void setDateRan(Date dateRan) {
		this.dateRan = dateRan;
	}

	@Column(name = "Meeting", nullable = false, length = 50)
	public String getMeeting() {
		return this.meeting;
	}

	public void setMeeting(String meeting) {
		this.meeting = meeting;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Bet_Fair_Imported", nullable = false)
	public boolean isBetFairImported() {
		return this.betFairImported;
	}

	public void setBetFairImported(boolean betFairImported) {
		this.betFairImported = betFairImported;
	}

	@Column(name = "Horse_Num", nullable = false)
	public int getHorseNum() {
		return this.horseNum;
	}

	public void setHorseNum(int horseNum) {
		this.horseNum = horseNum;
	}

	@Column(name = "raceCode", length = 10)
	public String getRaceCode() {
		return this.raceCode;
	}

	public void setRaceCode(String raceCode) {
		this.raceCode = raceCode;
	}

	@Column(name = "raceName", length = 200)
	public String getRaceName() {
		return this.raceName;
	}

	public void setRaceName(String raceName) {
		this.raceName = raceName;
	}

	@Column(name = "jockeyAccNo", length = 200)
	public String getJockeyAccNo() {
		return this.jockeyAccNo;
	}

	public void setJockeyAccNo(String jockeyAccNo) {
		this.jockeyAccNo = jockeyAccNo;
	}

}
