// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DisSubcategories generated by hbm2java
 */
@Entity
@Table(name = "dis_subcategories", catalog = "turf201_disciplinaries")
public class DisSubcategories implements java.io.Serializable {

	private Integer subId;
	private String subName;
	private int subCatId;

	public DisSubcategories() {
	}

	public DisSubcategories(String subName, int subCatId) {
		this.subName = subName;
		this.subCatId = subCatId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sub_id", unique = true, nullable = false)
	public Integer getSubId() {
		return this.subId;
	}

	public void setSubId(Integer subId) {
		this.subId = subId;
	}

	@Column(name = "sub_name", nullable = false, length = 65535)
	public String getSubName() {
		return this.subName;
	}

	public void setSubName(String subName) {
		this.subName = subName;
	}

	@Column(name = "sub_cat_id", nullable = false)
	public int getSubCatId() {
		return this.subCatId;
	}

	public void setSubCatId(int subCatId) {
		this.subCatId = subCatId;
	}

}
