// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DisTurfclubMessages generated by hbm2java
 */
@Entity
@Table(name = "dis_turfclub_messages", catalog = "turf201_disciplinaries")
public class DisTurfclubMessages implements java.io.Serializable {

	private Integer messageId;
	private String messageContent;
	private Date messageDisplayUntil;

	public DisTurfclubMessages() {
	}

	public DisTurfclubMessages(String messageContent, Date messageDisplayUntil) {
		this.messageContent = messageContent;
		this.messageDisplayUntil = messageDisplayUntil;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "message_id", unique = true, nullable = false)
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	@Column(name = "message_content", nullable = false, length = 16777215)
	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "message_display_until", nullable = false, length = 10)
	public Date getMessageDisplayUntil() {
		return this.messageDisplayUntil;
	}

	public void setMessageDisplayUntil(Date messageDisplayUntil) {
		this.messageDisplayUntil = messageDisplayUntil;
	}

}
