// default package
// Generated 31-Oct-2014 14:49:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DisVenues generated by hbm2java
 */
@Entity
@Table(name = "dis_venues", catalog = "turf201_disciplinaries")
public class DisVenues implements java.io.Serializable {

	private Integer venueId;
	private String venueName;
	private int venueRacecourseTypeId;
	private String venueShort;

	public DisVenues() {
	}

	public DisVenues(String venueName, int venueRacecourseTypeId,
			String venueShort) {
		this.venueName = venueName;
		this.venueRacecourseTypeId = venueRacecourseTypeId;
		this.venueShort = venueShort;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "venue_id", unique = true, nullable = false)
	public Integer getVenueId() {
		return this.venueId;
	}

	public void setVenueId(Integer venueId) {
		this.venueId = venueId;
	}

	@Column(name = "venue_name", nullable = false, length = 65535)
	public String getVenueName() {
		return this.venueName;
	}

	public void setVenueName(String venueName) {
		this.venueName = venueName;
	}

	@Column(name = "venue_racecourse_type_id", nullable = false)
	public int getVenueRacecourseTypeId() {
		return this.venueRacecourseTypeId;
	}

	public void setVenueRacecourseTypeId(int venueRacecourseTypeId) {
		this.venueRacecourseTypeId = venueRacecourseTypeId;
	}

	@Column(name = "venue_short", nullable = false, length = 65535)
	public String getVenueShort() {
		return this.venueShort;
	}

	public void setVenueShort(String venueShort) {
		this.venueShort = venueShort;
	}

}
