// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InspectionsSavedSearchesCategories generated by hbm2java
 */
@Entity
@Table(name = "inspections_saved_searches_categories", catalog = "inspections")
public class InspectionsSavedSearchesCategories implements java.io.Serializable {

	private InspectionsSavedSearchesCategoriesId id;

	public InspectionsSavedSearchesCategories() {
	}

	public InspectionsSavedSearchesCategories(
			InspectionsSavedSearchesCategoriesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "savedSearchId", column = @Column(name = "saved_search_id", nullable = false)),
			@AttributeOverride(name = "savedSearchCatId", column = @Column(name = "saved_search_cat_id", nullable = false)) })
	public InspectionsSavedSearchesCategoriesId getId() {
		return this.id;
	}

	public void setId(InspectionsSavedSearchesCategoriesId id) {
		this.id = id;
	}

}
