// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InspectionsSavedSearchesOfficials generated by hbm2java
 */
@Entity
@Table(name = "inspections_saved_searches_officials", catalog = "inspections")
public class InspectionsSavedSearchesOfficials implements java.io.Serializable {

	private InspectionsSavedSearchesOfficialsId id;

	public InspectionsSavedSearchesOfficials() {
	}

	public InspectionsSavedSearchesOfficials(
			InspectionsSavedSearchesOfficialsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "savedSearchId", column = @Column(name = "saved_search_id", nullable = false)),
			@AttributeOverride(name = "savedSearchOfficialId", column = @Column(name = "saved_search_official_id", nullable = false)) })
	public InspectionsSavedSearchesOfficialsId getId() {
		return this.id;
	}

	public void setId(InspectionsSavedSearchesOfficialsId id) {
		this.id = id;
	}

}
