// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InspectionsInspections generated by hbm2java
 */
@Entity
@Table(name = "inspections_inspections", catalog = "inspections")
public class InspectionsInspections implements java.io.Serializable {

	private Integer inspectionId;
	private Integer inspectionTrainerId;
	private Integer inspectionHandlerId;
	private Date inspectionDate;
	private int inspectionCategoryId;
	private int inspectionStatusId;
	private Integer inspectionSubCategoryId;
	private String inspectionDeptOfficials;

	public InspectionsInspections() {
	}

	public InspectionsInspections(Date inspectionDate,
			int inspectionCategoryId, int inspectionStatusId) {
		this.inspectionDate = inspectionDate;
		this.inspectionCategoryId = inspectionCategoryId;
		this.inspectionStatusId = inspectionStatusId;
	}

	public InspectionsInspections(Integer inspectionTrainerId,
			Integer inspectionHandlerId, Date inspectionDate,
			int inspectionCategoryId, int inspectionStatusId,
			Integer inspectionSubCategoryId, String inspectionDeptOfficials) {
		this.inspectionTrainerId = inspectionTrainerId;
		this.inspectionHandlerId = inspectionHandlerId;
		this.inspectionDate = inspectionDate;
		this.inspectionCategoryId = inspectionCategoryId;
		this.inspectionStatusId = inspectionStatusId;
		this.inspectionSubCategoryId = inspectionSubCategoryId;
		this.inspectionDeptOfficials = inspectionDeptOfficials;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "inspection_id", unique = true, nullable = false)
	public Integer getInspectionId() {
		return this.inspectionId;
	}

	public void setInspectionId(Integer inspectionId) {
		this.inspectionId = inspectionId;
	}

	@Column(name = "inspection_trainer_id")
	public Integer getInspectionTrainerId() {
		return this.inspectionTrainerId;
	}

	public void setInspectionTrainerId(Integer inspectionTrainerId) {
		this.inspectionTrainerId = inspectionTrainerId;
	}

	@Column(name = "inspection_handler_id")
	public Integer getInspectionHandlerId() {
		return this.inspectionHandlerId;
	}

	public void setInspectionHandlerId(Integer inspectionHandlerId) {
		this.inspectionHandlerId = inspectionHandlerId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inspection_date", nullable = false, length = 10)
	public Date getInspectionDate() {
		return this.inspectionDate;
	}

	public void setInspectionDate(Date inspectionDate) {
		this.inspectionDate = inspectionDate;
	}

	@Column(name = "inspection_category_id", nullable = false)
	public int getInspectionCategoryId() {
		return this.inspectionCategoryId;
	}

	public void setInspectionCategoryId(int inspectionCategoryId) {
		this.inspectionCategoryId = inspectionCategoryId;
	}

	@Column(name = "inspection_status_id", nullable = false)
	public int getInspectionStatusId() {
		return this.inspectionStatusId;
	}

	public void setInspectionStatusId(int inspectionStatusId) {
		this.inspectionStatusId = inspectionStatusId;
	}

	@Column(name = "inspection_sub_category_id")
	public Integer getInspectionSubCategoryId() {
		return this.inspectionSubCategoryId;
	}

	public void setInspectionSubCategoryId(Integer inspectionSubCategoryId) {
		this.inspectionSubCategoryId = inspectionSubCategoryId;
	}

	@Column(name = "inspection_dept_officials", length = 65535)
	public String getInspectionDeptOfficials() {
		return this.inspectionDeptOfficials;
	}

	public void setInspectionDeptOfficials(String inspectionDeptOfficials) {
		this.inspectionDeptOfficials = inspectionDeptOfficials;
	}

}
