// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InspectionsSavedSearchesDatesId generated by hbm2java
 */
@Embeddable
public class InspectionsSavedSearchesDatesId implements java.io.Serializable {

	private int savedSearchId;
	private Date savedSearchStartDate;
	private Date savedSearchEndDate;

	public InspectionsSavedSearchesDatesId() {
	}

	public InspectionsSavedSearchesDatesId(int savedSearchId) {
		this.savedSearchId = savedSearchId;
	}

	public InspectionsSavedSearchesDatesId(int savedSearchId,
			Date savedSearchStartDate, Date savedSearchEndDate) {
		this.savedSearchId = savedSearchId;
		this.savedSearchStartDate = savedSearchStartDate;
		this.savedSearchEndDate = savedSearchEndDate;
	}

	@Column(name = "saved_search_id", nullable = false)
	public int getSavedSearchId() {
		return this.savedSearchId;
	}

	public void setSavedSearchId(int savedSearchId) {
		this.savedSearchId = savedSearchId;
	}

	@Column(name = "saved_search_start_date", length = 10)
	public Date getSavedSearchStartDate() {
		return this.savedSearchStartDate;
	}

	public void setSavedSearchStartDate(Date savedSearchStartDate) {
		this.savedSearchStartDate = savedSearchStartDate;
	}

	@Column(name = "saved_search_end_date", length = 10)
	public Date getSavedSearchEndDate() {
		return this.savedSearchEndDate;
	}

	public void setSavedSearchEndDate(Date savedSearchEndDate) {
		this.savedSearchEndDate = savedSearchEndDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InspectionsSavedSearchesDatesId))
			return false;
		InspectionsSavedSearchesDatesId castOther = (InspectionsSavedSearchesDatesId) other;

		return (this.getSavedSearchId() == castOther.getSavedSearchId())
				&& ((this.getSavedSearchStartDate() == castOther
						.getSavedSearchStartDate()) || (this
						.getSavedSearchStartDate() != null
						&& castOther.getSavedSearchStartDate() != null && this
						.getSavedSearchStartDate().equals(
								castOther.getSavedSearchStartDate())))
				&& ((this.getSavedSearchEndDate() == castOther
						.getSavedSearchEndDate()) || (this
						.getSavedSearchEndDate() != null
						&& castOther.getSavedSearchEndDate() != null && this
						.getSavedSearchEndDate().equals(
								castOther.getSavedSearchEndDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSavedSearchId();
		result = 37
				* result
				+ (getSavedSearchStartDate() == null ? 0 : this
						.getSavedSearchStartDate().hashCode());
		result = 37
				* result
				+ (getSavedSearchEndDate() == null ? 0 : this
						.getSavedSearchEndDate().hashCode());
		return result;
	}

}
