// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InspectionsSavedSearchesCategoriesId generated by hbm2java
 */
@Embeddable
public class InspectionsSavedSearchesCategoriesId implements
		java.io.Serializable {

	private int savedSearchId;
	private int savedSearchCatId;

	public InspectionsSavedSearchesCategoriesId() {
	}

	public InspectionsSavedSearchesCategoriesId(int savedSearchId,
			int savedSearchCatId) {
		this.savedSearchId = savedSearchId;
		this.savedSearchCatId = savedSearchCatId;
	}

	@Column(name = "saved_search_id", nullable = false)
	public int getSavedSearchId() {
		return this.savedSearchId;
	}

	public void setSavedSearchId(int savedSearchId) {
		this.savedSearchId = savedSearchId;
	}

	@Column(name = "saved_search_cat_id", nullable = false)
	public int getSavedSearchCatId() {
		return this.savedSearchCatId;
	}

	public void setSavedSearchCatId(int savedSearchCatId) {
		this.savedSearchCatId = savedSearchCatId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InspectionsSavedSearchesCategoriesId))
			return false;
		InspectionsSavedSearchesCategoriesId castOther = (InspectionsSavedSearchesCategoriesId) other;

		return (this.getSavedSearchId() == castOther.getSavedSearchId())
				&& (this.getSavedSearchCatId() == castOther
						.getSavedSearchCatId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSavedSearchId();
		result = 37 * result + this.getSavedSearchCatId();
		return result;
	}

}
