// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InspectionsSavedSearchesStatus generated by hbm2java
 */
@Entity
@Table(name = "inspections_saved_searches_status", catalog = "inspections")
public class InspectionsSavedSearchesStatus implements java.io.Serializable {

	private InspectionsSavedSearchesStatusId id;

	public InspectionsSavedSearchesStatus() {
	}

	public InspectionsSavedSearchesStatus(InspectionsSavedSearchesStatusId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "savedSearchId", column = @Column(name = "saved_search_id", nullable = false)),
			@AttributeOverride(name = "savedStatusId", column = @Column(name = "saved_status_id", nullable = false)) })
	public InspectionsSavedSearchesStatusId getId() {
		return this.id;
	}

	public void setId(InspectionsSavedSearchesStatusId id) {
		this.id = id;
	}

}
