// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InspectionsSortBy generated by hbm2java
 */
@Entity
@Table(name = "inspections_sort_by", catalog = "inspections")
public class InspectionsSortBy implements java.io.Serializable {

	private Integer sortById;
	private String sortByName;
	private String sortByQuery;

	public InspectionsSortBy() {
	}

	public InspectionsSortBy(String sortByName, String sortByQuery) {
		this.sortByName = sortByName;
		this.sortByQuery = sortByQuery;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sort_by_id", unique = true, nullable = false)
	public Integer getSortById() {
		return this.sortById;
	}

	public void setSortById(Integer sortById) {
		this.sortById = sortById;
	}

	@Column(name = "sort_by_name", nullable = false, length = 200)
	public String getSortByName() {
		return this.sortByName;
	}

	public void setSortByName(String sortByName) {
		this.sortByName = sortByName;
	}

	@Column(name = "sort_by_query", nullable = false, length = 200)
	public String getSortByQuery() {
		return this.sortByQuery;
	}

	public void setSortByQuery(String sortByQuery) {
		this.sortByQuery = sortByQuery;
	}

}
