// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InspectionsSavedSearchesSubcategoriesId generated by hbm2java
 */
@Embeddable
public class InspectionsSavedSearchesSubcategoriesId implements
		java.io.Serializable {

	private int savedSearchId;
	private int savedSearchSubCatId;

	public InspectionsSavedSearchesSubcategoriesId() {
	}

	public InspectionsSavedSearchesSubcategoriesId(int savedSearchId,
			int savedSearchSubCatId) {
		this.savedSearchId = savedSearchId;
		this.savedSearchSubCatId = savedSearchSubCatId;
	}

	@Column(name = "saved_search_id", nullable = false)
	public int getSavedSearchId() {
		return this.savedSearchId;
	}

	public void setSavedSearchId(int savedSearchId) {
		this.savedSearchId = savedSearchId;
	}

	@Column(name = "saved_search_sub_cat_id", nullable = false)
	public int getSavedSearchSubCatId() {
		return this.savedSearchSubCatId;
	}

	public void setSavedSearchSubCatId(int savedSearchSubCatId) {
		this.savedSearchSubCatId = savedSearchSubCatId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InspectionsSavedSearchesSubcategoriesId))
			return false;
		InspectionsSavedSearchesSubcategoriesId castOther = (InspectionsSavedSearchesSubcategoriesId) other;

		return (this.getSavedSearchId() == castOther.getSavedSearchId())
				&& (this.getSavedSearchSubCatId() == castOther
						.getSavedSearchSubCatId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSavedSearchId();
		result = 37 * result + this.getSavedSearchSubCatId();
		return result;
	}

}
