// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InspectionsSavedSearchesStatusId generated by hbm2java
 */
@Embeddable
public class InspectionsSavedSearchesStatusId implements java.io.Serializable {

	private int savedSearchId;
	private int savedStatusId;

	public InspectionsSavedSearchesStatusId() {
	}

	public InspectionsSavedSearchesStatusId(int savedSearchId, int savedStatusId) {
		this.savedSearchId = savedSearchId;
		this.savedStatusId = savedStatusId;
	}

	@Column(name = "saved_search_id", nullable = false)
	public int getSavedSearchId() {
		return this.savedSearchId;
	}

	public void setSavedSearchId(int savedSearchId) {
		this.savedSearchId = savedSearchId;
	}

	@Column(name = "saved_status_id", nullable = false)
	public int getSavedStatusId() {
		return this.savedStatusId;
	}

	public void setSavedStatusId(int savedStatusId) {
		this.savedStatusId = savedStatusId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InspectionsSavedSearchesStatusId))
			return false;
		InspectionsSavedSearchesStatusId castOther = (InspectionsSavedSearchesStatusId) other;

		return (this.getSavedSearchId() == castOther.getSavedSearchId())
				&& (this.getSavedStatusId() == castOther.getSavedStatusId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSavedSearchId();
		result = 37 * result + this.getSavedStatusId();
		return result;
	}

}
