// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InspectionsSavedSearchesOfficialsId generated by hbm2java
 */
@Embeddable
public class InspectionsSavedSearchesOfficialsId implements
		java.io.Serializable {

	private int savedSearchId;
	private int savedSearchOfficialId;

	public InspectionsSavedSearchesOfficialsId() {
	}

	public InspectionsSavedSearchesOfficialsId(int savedSearchId,
			int savedSearchOfficialId) {
		this.savedSearchId = savedSearchId;
		this.savedSearchOfficialId = savedSearchOfficialId;
	}

	@Column(name = "saved_search_id", nullable = false)
	public int getSavedSearchId() {
		return this.savedSearchId;
	}

	public void setSavedSearchId(int savedSearchId) {
		this.savedSearchId = savedSearchId;
	}

	@Column(name = "saved_search_official_id", nullable = false)
	public int getSavedSearchOfficialId() {
		return this.savedSearchOfficialId;
	}

	public void setSavedSearchOfficialId(int savedSearchOfficialId) {
		this.savedSearchOfficialId = savedSearchOfficialId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InspectionsSavedSearchesOfficialsId))
			return false;
		InspectionsSavedSearchesOfficialsId castOther = (InspectionsSavedSearchesOfficialsId) other;

		return (this.getSavedSearchId() == castOther.getSavedSearchId())
				&& (this.getSavedSearchOfficialId() == castOther
						.getSavedSearchOfficialId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSavedSearchId();
		result = 37 * result + this.getSavedSearchOfficialId();
		return result;
	}

}
