// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InspectionsSavedSearchesSubcategories generated by hbm2java
 */
@Entity
@Table(name = "inspections_saved_searches_subcategories", catalog = "inspections")
public class InspectionsSavedSearchesSubcategories implements
		java.io.Serializable {

	private InspectionsSavedSearchesSubcategoriesId id;

	public InspectionsSavedSearchesSubcategories() {
	}

	public InspectionsSavedSearchesSubcategories(
			InspectionsSavedSearchesSubcategoriesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "savedSearchId", column = @Column(name = "saved_search_id", nullable = false)),
			@AttributeOverride(name = "savedSearchSubCatId", column = @Column(name = "saved_search_sub_cat_id", nullable = false)) })
	public InspectionsSavedSearchesSubcategoriesId getId() {
		return this.id;
	}

	public void setId(InspectionsSavedSearchesSubcategoriesId id) {
		this.id = id;
	}

}
