// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InspectionsSavedSearches generated by hbm2java
 */
@Entity
@Table(name = "inspections_saved_searches", catalog = "inspections")
public class InspectionsSavedSearches implements java.io.Serializable {

	private Integer savedSearchId;
	private int savedSearchUserId;
	private String savedSearchTrainer;
	private String savedSearchDeptOfficial;
	private int savedSearchMaxResults;

	public InspectionsSavedSearches() {
	}

	public InspectionsSavedSearches(int savedSearchUserId,
			int savedSearchMaxResults) {
		this.savedSearchUserId = savedSearchUserId;
		this.savedSearchMaxResults = savedSearchMaxResults;
	}

	public InspectionsSavedSearches(int savedSearchUserId,
			String savedSearchTrainer, String savedSearchDeptOfficial,
			int savedSearchMaxResults) {
		this.savedSearchUserId = savedSearchUserId;
		this.savedSearchTrainer = savedSearchTrainer;
		this.savedSearchDeptOfficial = savedSearchDeptOfficial;
		this.savedSearchMaxResults = savedSearchMaxResults;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "saved_search_id", unique = true, nullable = false)
	public Integer getSavedSearchId() {
		return this.savedSearchId;
	}

	public void setSavedSearchId(Integer savedSearchId) {
		this.savedSearchId = savedSearchId;
	}

	@Column(name = "saved_search_user_id", nullable = false)
	public int getSavedSearchUserId() {
		return this.savedSearchUserId;
	}

	public void setSavedSearchUserId(int savedSearchUserId) {
		this.savedSearchUserId = savedSearchUserId;
	}

	@Column(name = "saved_search_trainer", length = 200)
	public String getSavedSearchTrainer() {
		return this.savedSearchTrainer;
	}

	public void setSavedSearchTrainer(String savedSearchTrainer) {
		this.savedSearchTrainer = savedSearchTrainer;
	}

	@Column(name = "saved_search_dept_official", length = 200)
	public String getSavedSearchDeptOfficial() {
		return this.savedSearchDeptOfficial;
	}

	public void setSavedSearchDeptOfficial(String savedSearchDeptOfficial) {
		this.savedSearchDeptOfficial = savedSearchDeptOfficial;
	}

	@Column(name = "saved_search_max_results", nullable = false)
	public int getSavedSearchMaxResults() {
		return this.savedSearchMaxResults;
	}

	public void setSavedSearchMaxResults(int savedSearchMaxResults) {
		this.savedSearchMaxResults = savedSearchMaxResults;
	}

}
