// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InspectionsHandlers generated by hbm2java
 */
@Entity
@Table(name = "inspections_handlers", catalog = "inspections")
public class InspectionsHandlers implements java.io.Serializable {

	private InspectionsHandlersId id;

	public InspectionsHandlers() {
	}

	public InspectionsHandlers(InspectionsHandlersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ownerId", column = @Column(name = "owner_id", nullable = false)),
			@AttributeOverride(name = "ownerFirstName", column = @Column(name = "owner_first_name", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerAccountNo", column = @Column(name = "owner_account_no", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerSurname", column = @Column(name = "owner_surname", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerAddress1", column = @Column(name = "owner_address1", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerAddress2", column = @Column(name = "owner_address2", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerAddress3", column = @Column(name = "owner_address3", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerAddress4", column = @Column(name = "owner_address4", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerMobileNo", column = @Column(name = "owner_mobile_no", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerPhoneNo", column = @Column(name = "owner_phone_no", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerEmail", column = @Column(name = "owner_email", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerDateOfBirth", column = @Column(name = "owner_date_of_birth", nullable = false, length = 10)),
			@AttributeOverride(name = "ownerHriAccNo", column = @Column(name = "owner_hri_acc_no", nullable = false, length = 200)),
			@AttributeOverride(name = "ownerStatus", column = @Column(name = "owner_status", nullable = false, length = 200)) })
	public InspectionsHandlersId getId() {
		return this.id;
	}

	public void setId(InspectionsHandlersId id) {
		this.id = id;
	}

}
