// default package
// Generated 13-Feb-2015 16:15:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InspectionsTypes generated by hbm2java
 */
@Entity
@Table(name = "inspections_types", catalog = "inspections")
public class InspectionsTypes implements java.io.Serializable {

	private Integer typeId;
	private String typeName;

	public InspectionsTypes() {
	}

	public InspectionsTypes(String typeName) {
		this.typeName = typeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "type_id", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "type_name", nullable = false, length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
