// default package
// Generated 15-Oct-2014 16:45:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MeetingsTableExportId generated by hbm2java
 */
@Embeddable
public class MeetingsTableExportId implements java.io.Serializable {

	private Date MDate;
	private String MName;

	public MeetingsTableExportId() {
	}

	public MeetingsTableExportId(Date MDate, String MName) {
		this.MDate = MDate;
		this.MName = MName;
	}

	@Column(name = "M_Date", length = 19)
	public Date getMDate() {
		return this.MDate;
	}

	public void setMDate(Date MDate) {
		this.MDate = MDate;
	}

	@Column(name = "M_Name", length = 250)
	public String getMName() {
		return this.MName;
	}

	public void setMName(String MName) {
		this.MName = MName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MeetingsTableExportId))
			return false;
		MeetingsTableExportId castOther = (MeetingsTableExportId) other;

		return ((this.getMDate() == castOther.getMDate()) || (this.getMDate() != null
				&& castOther.getMDate() != null && this.getMDate().equals(
				castOther.getMDate())))
				&& ((this.getMName() == castOther.getMName()) || (this
						.getMName() != null && castOther.getMName() != null && this
						.getMName().equals(castOther.getMName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMDate() == null ? 0 : this.getMDate().hashCode());
		result = 37 * result
				+ (getMName() == null ? 0 : this.getMName().hashCode());
		return result;
	}

}
