// default package
// Generated 15-Oct-2014 16:45:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MeetingsTableExport generated by hbm2java
 */
@Entity
@Table(name = "MeetingsTableExport", catalog = "p2p")
public class MeetingsTableExport implements java.io.Serializable {

	private MeetingsTableExportId id;

	public MeetingsTableExport() {
	}

	public MeetingsTableExport(MeetingsTableExportId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "MDate", column = @Column(name = "M_Date", length = 19)),
			@AttributeOverride(name = "MName", column = @Column(name = "M_Name", length = 250)) })
	public MeetingsTableExportId getId() {
		return this.id;
	}

	public void setId(MeetingsTableExportId id) {
		this.id = id;
	}

}
