// default package
// Generated 15-Oct-2014 16:45:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * P2pHandlers generated by hbm2java
 */
@Entity
@Table(name = "p2p_handlers", catalog = "p2p")
public class P2pHandlers implements java.io.Serializable {

	private Integer handId;
	private int handRecordNo;
	private String handAccountNo;
	private String handFirstname;
	private String handSurname;
	private String handAddress1;
	private String handAddress2;
	private String handAddress3;
	private String handAddress4;
	private String handMobileNo;
	private String handPhoneNo;
	private Date handDob;
	private String handEmail;
	private String handRaceCardName;
	private Boolean handDataProtection;
	private Date handDateRenewed;
	private Date handDateChanged;
	private String handPwd;
	private String handPwdMd5;
	private String handInsuranceCompany;
	private String handInsurancePolicyNo;
	private String handForfeitList;
	private boolean handRenewed;

	public P2pHandlers() {
	}

	public P2pHandlers(int handRecordNo, String handAccountNo,
			String handFirstname, String handSurname, String handAddress1,
			String handRaceCardName, String handPwd, boolean handRenewed) {
		this.handRecordNo = handRecordNo;
		this.handAccountNo = handAccountNo;
		this.handFirstname = handFirstname;
		this.handSurname = handSurname;
		this.handAddress1 = handAddress1;
		this.handRaceCardName = handRaceCardName;
		this.handPwd = handPwd;
		this.handRenewed = handRenewed;
	}

	public P2pHandlers(int handRecordNo, String handAccountNo,
			String handFirstname, String handSurname, String handAddress1,
			String handAddress2, String handAddress3, String handAddress4,
			String handMobileNo, String handPhoneNo, Date handDob,
			String handEmail, String handRaceCardName,
			Boolean handDataProtection, Date handDateRenewed,
			Date handDateChanged, String handPwd, String handPwdMd5,
			String handInsuranceCompany, String handInsurancePolicyNo,
			String handForfeitList, boolean handRenewed) {
		this.handRecordNo = handRecordNo;
		this.handAccountNo = handAccountNo;
		this.handFirstname = handFirstname;
		this.handSurname = handSurname;
		this.handAddress1 = handAddress1;
		this.handAddress2 = handAddress2;
		this.handAddress3 = handAddress3;
		this.handAddress4 = handAddress4;
		this.handMobileNo = handMobileNo;
		this.handPhoneNo = handPhoneNo;
		this.handDob = handDob;
		this.handEmail = handEmail;
		this.handRaceCardName = handRaceCardName;
		this.handDataProtection = handDataProtection;
		this.handDateRenewed = handDateRenewed;
		this.handDateChanged = handDateChanged;
		this.handPwd = handPwd;
		this.handPwdMd5 = handPwdMd5;
		this.handInsuranceCompany = handInsuranceCompany;
		this.handInsurancePolicyNo = handInsurancePolicyNo;
		this.handForfeitList = handForfeitList;
		this.handRenewed = handRenewed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hand_id", unique = true, nullable = false)
	public Integer getHandId() {
		return this.handId;
	}

	public void setHandId(Integer handId) {
		this.handId = handId;
	}

	@Column(name = "hand_record_no", nullable = false)
	public int getHandRecordNo() {
		return this.handRecordNo;
	}

	public void setHandRecordNo(int handRecordNo) {
		this.handRecordNo = handRecordNo;
	}

	@Column(name = "hand_account_no", nullable = false, length = 8)
	public String getHandAccountNo() {
		return this.handAccountNo;
	}

	public void setHandAccountNo(String handAccountNo) {
		this.handAccountNo = handAccountNo;
	}

	@Column(name = "hand_firstname", nullable = false, length = 250)
	public String getHandFirstname() {
		return this.handFirstname;
	}

	public void setHandFirstname(String handFirstname) {
		this.handFirstname = handFirstname;
	}

	@Column(name = "hand_surname", nullable = false, length = 250)
	public String getHandSurname() {
		return this.handSurname;
	}

	public void setHandSurname(String handSurname) {
		this.handSurname = handSurname;
	}

	@Column(name = "hand_address1", nullable = false, length = 250)
	public String getHandAddress1() {
		return this.handAddress1;
	}

	public void setHandAddress1(String handAddress1) {
		this.handAddress1 = handAddress1;
	}

	@Column(name = "hand_address2", length = 250)
	public String getHandAddress2() {
		return this.handAddress2;
	}

	public void setHandAddress2(String handAddress2) {
		this.handAddress2 = handAddress2;
	}

	@Column(name = "hand_address3", length = 250)
	public String getHandAddress3() {
		return this.handAddress3;
	}

	public void setHandAddress3(String handAddress3) {
		this.handAddress3 = handAddress3;
	}

	@Column(name = "hand_address4", length = 250)
	public String getHandAddress4() {
		return this.handAddress4;
	}

	public void setHandAddress4(String handAddress4) {
		this.handAddress4 = handAddress4;
	}

	@Column(name = "hand_mobile_no", length = 20)
	public String getHandMobileNo() {
		return this.handMobileNo;
	}

	public void setHandMobileNo(String handMobileNo) {
		this.handMobileNo = handMobileNo;
	}

	@Column(name = "hand_phone_no", length = 20)
	public String getHandPhoneNo() {
		return this.handPhoneNo;
	}

	public void setHandPhoneNo(String handPhoneNo) {
		this.handPhoneNo = handPhoneNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hand_dob", length = 10)
	public Date getHandDob() {
		return this.handDob;
	}

	public void setHandDob(Date handDob) {
		this.handDob = handDob;
	}

	@Column(name = "hand_email", length = 100)
	public String getHandEmail() {
		return this.handEmail;
	}

	public void setHandEmail(String handEmail) {
		this.handEmail = handEmail;
	}

	@Column(name = "hand_race_card_name", nullable = false, length = 250)
	public String getHandRaceCardName() {
		return this.handRaceCardName;
	}

	public void setHandRaceCardName(String handRaceCardName) {
		this.handRaceCardName = handRaceCardName;
	}

	@Column(name = "hand_data_protection")
	public Boolean getHandDataProtection() {
		return this.handDataProtection;
	}

	public void setHandDataProtection(Boolean handDataProtection) {
		this.handDataProtection = handDataProtection;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hand_date_renewed", length = 10)
	public Date getHandDateRenewed() {
		return this.handDateRenewed;
	}

	public void setHandDateRenewed(Date handDateRenewed) {
		this.handDateRenewed = handDateRenewed;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hand_date_changed", length = 10)
	public Date getHandDateChanged() {
		return this.handDateChanged;
	}

	public void setHandDateChanged(Date handDateChanged) {
		this.handDateChanged = handDateChanged;
	}

	@Column(name = "hand_pwd", nullable = false, length = 250)
	public String getHandPwd() {
		return this.handPwd;
	}

	public void setHandPwd(String handPwd) {
		this.handPwd = handPwd;
	}

	@Column(name = "hand_pwd_md5", length = 250)
	public String getHandPwdMd5() {
		return this.handPwdMd5;
	}

	public void setHandPwdMd5(String handPwdMd5) {
		this.handPwdMd5 = handPwdMd5;
	}

	@Column(name = "hand_insurance_company", length = 250)
	public String getHandInsuranceCompany() {
		return this.handInsuranceCompany;
	}

	public void setHandInsuranceCompany(String handInsuranceCompany) {
		this.handInsuranceCompany = handInsuranceCompany;
	}

	@Column(name = "hand_insurance_policy_no", length = 100)
	public String getHandInsurancePolicyNo() {
		return this.handInsurancePolicyNo;
	}

	public void setHandInsurancePolicyNo(String handInsurancePolicyNo) {
		this.handInsurancePolicyNo = handInsurancePolicyNo;
	}

	@Column(name = "hand_forfeit_list", length = 250)
	public String getHandForfeitList() {
		return this.handForfeitList;
	}

	public void setHandForfeitList(String handForfeitList) {
		this.handForfeitList = handForfeitList;
	}

	@Column(name = "hand_renewed", nullable = false)
	public boolean isHandRenewed() {
		return this.handRenewed;
	}

	public void setHandRenewed(boolean handRenewed) {
		this.handRenewed = handRenewed;
	}

}
