// default package
// Generated 15-Oct-2014 16:45:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * P2pHuntercertsSales generated by hbm2java
 */
@Entity
@Table(name = "p2p_huntercerts_sales", catalog = "p2p")
public class P2pHuntercertsSales implements java.io.Serializable {

	private String salesOrderId;
	private P2pHunterCerts p2pHunterCerts;
	private String salesAmount;
	private String salesPayee;

	public P2pHuntercertsSales() {
	}

	public P2pHuntercertsSales(P2pHunterCerts p2pHunterCerts,
			String salesAmount, String salesPayee) {
		this.p2pHunterCerts = p2pHunterCerts;
		this.salesAmount = salesAmount;
		this.salesPayee = salesPayee;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "p2pHunterCerts"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "sales_order_id", unique = true, nullable = false, length = 12)
	public String getSalesOrderId() {
		return this.salesOrderId;
	}

	public void setSalesOrderId(String salesOrderId) {
		this.salesOrderId = salesOrderId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public P2pHunterCerts getP2pHunterCerts() {
		return this.p2pHunterCerts;
	}

	public void setP2pHunterCerts(P2pHunterCerts p2pHunterCerts) {
		this.p2pHunterCerts = p2pHunterCerts;
	}

	@Column(name = "sales_amount", nullable = false, length = 10)
	public String getSalesAmount() {
		return this.salesAmount;
	}

	public void setSalesAmount(String salesAmount) {
		this.salesAmount = salesAmount;
	}

	@Column(name = "sales_payee", nullable = false, length = 200)
	public String getSalesPayee() {
		return this.salesPayee;
	}

	public void setSalesPayee(String salesPayee) {
		this.salesPayee = salesPayee;
	}

}
