// default package
// Generated 15-Oct-2014 16:45:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * P2pVaccinations generated by hbm2java
 */
@Entity
@Table(name = "p2p_vaccinations", catalog = "p2p")
public class P2pVaccinations implements java.io.Serializable {

	private Integer vacId;
	private int vacHcertId;
	private Date vacDate;
	private String vacType;

	public P2pVaccinations() {
	}

	public P2pVaccinations(int vacHcertId, Date vacDate, String vacType) {
		this.vacHcertId = vacHcertId;
		this.vacDate = vacDate;
		this.vacType = vacType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vac_id", unique = true, nullable = false)
	public Integer getVacId() {
		return this.vacId;
	}

	public void setVacId(Integer vacId) {
		this.vacId = vacId;
	}

	@Column(name = "vac_hcert_id", nullable = false)
	public int getVacHcertId() {
		return this.vacHcertId;
	}

	public void setVacHcertId(int vacHcertId) {
		this.vacHcertId = vacHcertId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vac_date", nullable = false, length = 10)
	public Date getVacDate() {
		return this.vacDate;
	}

	public void setVacDate(Date vacDate) {
		this.vacDate = vacDate;
	}

	@Column(name = "vac_type", nullable = false, length = 5)
	public String getVacType() {
		return this.vacType;
	}

	public void setVacType(String vacType) {
		this.vacType = vacType;
	}

}
