// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Sheet1 generated by hbm2java
 */
@Entity
@Table(name = "Sheet1", catalog = "inspections")
public class Sheet1 implements java.io.Serializable {

	private Sheet1Id id;

	public Sheet1() {
	}

	public Sheet1(Sheet1Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "a", column = @Column(name = "A", length = 29)),
			@AttributeOverride(name = "b", column = @Column(name = "B", length = 57)),
			@AttributeOverride(name = "c", column = @Column(name = "C", length = 10)),
			@AttributeOverride(name = "d", column = @Column(name = "D", length = 10)),
			@AttributeOverride(name = "e", column = @Column(name = "E", length = 26)) })
	public Sheet1Id getId() {
		return this.id;
	}

	public void setId(Sheet1Id id) {
		this.id = id;
	}

}
