// default package
// Generated 28-Apr-2015 14:57:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TeEmployentHistory generated by hbm2java
 */
@Entity
@Table(name = "te_employent_history", catalog = "trainers_employees")
public class TeEmployentHistory implements java.io.Serializable {

	private Integer ehEmploymentId;
	private TeEmployees teEmployees;
	private TeTrainers teTrainers;
	private TeCards teCards;
	private String ehCardType;
	private Date ehDateFrom;
	private Date ehDateTo;
	private Float ehHoursWorked;
	private String ehEmploymentCategory;
	private String ehYear;
	private Float ehEarnings;
	private String ehTempCategory;

	public TeEmployentHistory() {
	}

	public TeEmployentHistory(TeEmployees teEmployees, TeTrainers teTrainers,
			Date ehDateFrom) {
		this.teEmployees = teEmployees;
		this.teTrainers = teTrainers;
		this.ehDateFrom = ehDateFrom;
	}

	public TeEmployentHistory(TeEmployees teEmployees, TeTrainers teTrainers,
			TeCards teCards, String ehCardType, Date ehDateFrom, Date ehDateTo,
			Float ehHoursWorked, String ehEmploymentCategory, String ehYear,
			Float ehEarnings, String ehTempCategory) {
		this.teEmployees = teEmployees;
		this.teTrainers = teTrainers;
		this.teCards = teCards;
		this.ehCardType = ehCardType;
		this.ehDateFrom = ehDateFrom;
		this.ehDateTo = ehDateTo;
		this.ehHoursWorked = ehHoursWorked;
		this.ehEmploymentCategory = ehEmploymentCategory;
		this.ehYear = ehYear;
		this.ehEarnings = ehEarnings;
		this.ehTempCategory = ehTempCategory;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "eh_employment_id", unique = true, nullable = false)
	public Integer getEhEmploymentId() {
		return this.ehEmploymentId;
	}

	public void setEhEmploymentId(Integer ehEmploymentId) {
		this.ehEmploymentId = ehEmploymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eh_employee_id", nullable = false)
	public TeEmployees getTeEmployees() {
		return this.teEmployees;
	}

	public void setTeEmployees(TeEmployees teEmployees) {
		this.teEmployees = teEmployees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eh_trainer_id", nullable = false)
	public TeTrainers getTeTrainers() {
		return this.teTrainers;
	}

	public void setTeTrainers(TeTrainers teTrainers) {
		this.teTrainers = teTrainers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eh_card_id")
	public TeCards getTeCards() {
		return this.teCards;
	}

	public void setTeCards(TeCards teCards) {
		this.teCards = teCards;
	}

	@Column(name = "eh_card_type", length = 2)
	public String getEhCardType() {
		return this.ehCardType;
	}

	public void setEhCardType(String ehCardType) {
		this.ehCardType = ehCardType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "eh_date_from", nullable = false, length = 10)
	public Date getEhDateFrom() {
		return this.ehDateFrom;
	}

	public void setEhDateFrom(Date ehDateFrom) {
		this.ehDateFrom = ehDateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "eh_date_to", length = 10)
	public Date getEhDateTo() {
		return this.ehDateTo;
	}

	public void setEhDateTo(Date ehDateTo) {
		this.ehDateTo = ehDateTo;
	}

	@Column(name = "eh_hours_worked", precision = 12, scale = 0)
	public Float getEhHoursWorked() {
		return this.ehHoursWorked;
	}

	public void setEhHoursWorked(Float ehHoursWorked) {
		this.ehHoursWorked = ehHoursWorked;
	}

	@Column(name = "eh_employment_category", length = 26)
	public String getEhEmploymentCategory() {
		return this.ehEmploymentCategory;
	}

	public void setEhEmploymentCategory(String ehEmploymentCategory) {
		this.ehEmploymentCategory = ehEmploymentCategory;
	}

	@Column(name = "eh_year", length = 4)
	public String getEhYear() {
		return this.ehYear;
	}

	public void setEhYear(String ehYear) {
		this.ehYear = ehYear;
	}

	@Column(name = "eh_earnings", precision = 12, scale = 0)
	public Float getEhEarnings() {
		return this.ehEarnings;
	}

	public void setEhEarnings(Float ehEarnings) {
		this.ehEarnings = ehEarnings;
	}

	@Column(name = "eh_temp_category", length = 200)
	public String getEhTempCategory() {
		return this.ehTempCategory;
	}

	public void setEhTempCategory(String ehTempCategory) {
		this.ehTempCategory = ehTempCategory;
	}

}
