// default package
// Generated 28-Apr-2015 14:52:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TempInspections generated by hbm2java
 */
@Entity
@Table(name = "temp_inspections", catalog = "inspections")
public class TempInspections implements java.io.Serializable {

	private Integer tempId;
	private Integer tempTrainerId;
	private String tempTrainerFirstName;
	private String tempTrainerSurName;
	private String tempTrainerAddress;
	private String tempTrainerNameFromFile;
	private String tempTrainerAddressFromFile;
	private Date tempDate;
	private int tempCatId;
	private int tempSubCatId;
	private Integer tempHandlerId;

	public TempInspections() {
	}

	public TempInspections(Date tempDate, int tempCatId, int tempSubCatId) {
		this.tempDate = tempDate;
		this.tempCatId = tempCatId;
		this.tempSubCatId = tempSubCatId;
	}

	public TempInspections(Integer tempTrainerId, String tempTrainerFirstName,
			String tempTrainerSurName, String tempTrainerAddress,
			String tempTrainerNameFromFile, String tempTrainerAddressFromFile,
			Date tempDate, int tempCatId, int tempSubCatId,
			Integer tempHandlerId) {
		this.tempTrainerId = tempTrainerId;
		this.tempTrainerFirstName = tempTrainerFirstName;
		this.tempTrainerSurName = tempTrainerSurName;
		this.tempTrainerAddress = tempTrainerAddress;
		this.tempTrainerNameFromFile = tempTrainerNameFromFile;
		this.tempTrainerAddressFromFile = tempTrainerAddressFromFile;
		this.tempDate = tempDate;
		this.tempCatId = tempCatId;
		this.tempSubCatId = tempSubCatId;
		this.tempHandlerId = tempHandlerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "temp_id", unique = true, nullable = false)
	public Integer getTempId() {
		return this.tempId;
	}

	public void setTempId(Integer tempId) {
		this.tempId = tempId;
	}

	@Column(name = "temp_trainer_id")
	public Integer getTempTrainerId() {
		return this.tempTrainerId;
	}

	public void setTempTrainerId(Integer tempTrainerId) {
		this.tempTrainerId = tempTrainerId;
	}

	@Column(name = "temp_trainer_first_name", length = 200)
	public String getTempTrainerFirstName() {
		return this.tempTrainerFirstName;
	}

	public void setTempTrainerFirstName(String tempTrainerFirstName) {
		this.tempTrainerFirstName = tempTrainerFirstName;
	}

	@Column(name = "temp_trainer_sur_name", length = 200)
	public String getTempTrainerSurName() {
		return this.tempTrainerSurName;
	}

	public void setTempTrainerSurName(String tempTrainerSurName) {
		this.tempTrainerSurName = tempTrainerSurName;
	}

	@Column(name = "temp_trainer_address", length = 65535)
	public String getTempTrainerAddress() {
		return this.tempTrainerAddress;
	}

	public void setTempTrainerAddress(String tempTrainerAddress) {
		this.tempTrainerAddress = tempTrainerAddress;
	}

	@Column(name = "temp_trainer_name_from_file", length = 200)
	public String getTempTrainerNameFromFile() {
		return this.tempTrainerNameFromFile;
	}

	public void setTempTrainerNameFromFile(String tempTrainerNameFromFile) {
		this.tempTrainerNameFromFile = tempTrainerNameFromFile;
	}

	@Column(name = "temp_trainer_address_from_file", length = 65535)
	public String getTempTrainerAddressFromFile() {
		return this.tempTrainerAddressFromFile;
	}

	public void setTempTrainerAddressFromFile(String tempTrainerAddressFromFile) {
		this.tempTrainerAddressFromFile = tempTrainerAddressFromFile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "temp_date", nullable = false, length = 10)
	public Date getTempDate() {
		return this.tempDate;
	}

	public void setTempDate(Date tempDate) {
		this.tempDate = tempDate;
	}

	@Column(name = "temp_cat_id", nullable = false)
	public int getTempCatId() {
		return this.tempCatId;
	}

	public void setTempCatId(int tempCatId) {
		this.tempCatId = tempCatId;
	}

	@Column(name = "temp_sub_cat_id", nullable = false)
	public int getTempSubCatId() {
		return this.tempSubCatId;
	}

	public void setTempSubCatId(int tempSubCatId) {
		this.tempSubCatId = tempSubCatId;
	}

	@Column(name = "temp_handler_id")
	public Integer getTempHandlerId() {
		return this.tempHandlerId;
	}

	public void setTempHandlerId(Integer tempHandlerId) {
		this.tempHandlerId = tempHandlerId;
	}

}
