// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VetreportTrainers generated by hbm2java
 */
@Entity
@Table(name = "vetreport_trainers", catalog = "vetreports")
public class VetreportTrainers implements java.io.Serializable {

	private VetreportTrainersId id;

	public VetreportTrainers() {
	}

	public VetreportTrainers(VetreportTrainersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "trainerId", column = @Column(name = "trainer_id", nullable = false)),
			@AttributeOverride(name = "trainerName", column = @Column(name = "trainer_name", nullable = false, length = 200)) })
	public VetreportTrainersId getId() {
		return this.id;
	}

	public void setId(VetreportTrainersId id) {
		this.id = id;
	}

}
