// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VetreportAlertHorsesWithTrainerId generated by hbm2java
 */
@Embeddable
public class VetreportAlertHorsesWithTrainerId implements java.io.Serializable {

	private String alertId;
	private String alertHorseName;
	private String alertTrainerName;

	public VetreportAlertHorsesWithTrainerId() {
	}

	public VetreportAlertHorsesWithTrainerId(String alertTrainerName) {
		this.alertTrainerName = alertTrainerName;
	}

	public VetreportAlertHorsesWithTrainerId(String alertId,
			String alertHorseName, String alertTrainerName) {
		this.alertId = alertId;
		this.alertHorseName = alertHorseName;
		this.alertTrainerName = alertTrainerName;
	}

	@Column(name = "alert_id", length = 21)
	public String getAlertId() {
		return this.alertId;
	}

	public void setAlertId(String alertId) {
		this.alertId = alertId;
	}

	@Column(name = "alert_horse_name", length = 200)
	public String getAlertHorseName() {
		return this.alertHorseName;
	}

	public void setAlertHorseName(String alertHorseName) {
		this.alertHorseName = alertHorseName;
	}

	@Column(name = "alert_trainer_name", nullable = false, length = 200)
	public String getAlertTrainerName() {
		return this.alertTrainerName;
	}

	public void setAlertTrainerName(String alertTrainerName) {
		this.alertTrainerName = alertTrainerName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VetreportAlertHorsesWithTrainerId))
			return false;
		VetreportAlertHorsesWithTrainerId castOther = (VetreportAlertHorsesWithTrainerId) other;

		return ((this.getAlertId() == castOther.getAlertId()) || (this
				.getAlertId() != null && castOther.getAlertId() != null && this
				.getAlertId().equals(castOther.getAlertId())))
				&& ((this.getAlertHorseName() == castOther.getAlertHorseName()) || (this
						.getAlertHorseName() != null
						&& castOther.getAlertHorseName() != null && this
						.getAlertHorseName().equals(
								castOther.getAlertHorseName())))
				&& ((this.getAlertTrainerName() == castOther
						.getAlertTrainerName()) || (this.getAlertTrainerName() != null
						&& castOther.getAlertTrainerName() != null && this
						.getAlertTrainerName().equals(
								castOther.getAlertTrainerName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAlertId() == null ? 0 : this.getAlertId().hashCode());
		result = 37
				* result
				+ (getAlertHorseName() == null ? 0 : this.getAlertHorseName()
						.hashCode());
		result = 37
				* result
				+ (getAlertTrainerName() == null ? 0 : this
						.getAlertTrainerName().hashCode());
		return result;
	}

}
