// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VetreportHorsesNoFormId generated by hbm2java
 */
@Embeddable
public class VetreportHorsesNoFormId implements java.io.Serializable {

	private int rowId;
	private String horseName;

	public VetreportHorsesNoFormId() {
	}

	public VetreportHorsesNoFormId(int rowId, String horseName) {
		this.rowId = rowId;
		this.horseName = horseName;
	}

	@Column(name = "row_id", nullable = false)
	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	@Column(name = "Horse_Name", nullable = false, length = 50)
	public String getHorseName() {
		return this.horseName;
	}

	public void setHorseName(String horseName) {
		this.horseName = horseName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VetreportHorsesNoFormId))
			return false;
		VetreportHorsesNoFormId castOther = (VetreportHorsesNoFormId) other;

		return (this.getRowId() == castOther.getRowId())
				&& ((this.getHorseName() == castOther.getHorseName()) || (this
						.getHorseName() != null
						&& castOther.getHorseName() != null && this
						.getHorseName().equals(castOther.getHorseName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRowId();
		result = 37 * result
				+ (getHorseName() == null ? 0 : this.getHorseName().hashCode());
		return result;
	}

}
