// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VetreportReports generated by hbm2java
 */
@Entity
@Table(name = "vetreport_reports", catalog = "vetreports")
public class VetreportReports implements java.io.Serializable {

	private Integer reportId;
	private String reportContent;
	private Integer reportRacecardId;
	private Integer reportRandomId;
	private Integer reportNonRunnerId;
	private String reportMisc;
	private String reportHorsePlaced;
	private String tempVetNames;
	private String reportType;
	private String tempHorsename;
	private String tempDate;
	private String tempTrainer;

	public VetreportReports() {
	}

	public VetreportReports(String reportContent, String tempVetNames,
			String reportType) {
		this.reportContent = reportContent;
		this.tempVetNames = tempVetNames;
		this.reportType = reportType;
	}

	public VetreportReports(String reportContent, Integer reportRacecardId,
			Integer reportRandomId, Integer reportNonRunnerId,
			String reportMisc, String reportHorsePlaced, String tempVetNames,
			String reportType, String tempHorsename, String tempDate,
			String tempTrainer) {
		this.reportContent = reportContent;
		this.reportRacecardId = reportRacecardId;
		this.reportRandomId = reportRandomId;
		this.reportNonRunnerId = reportNonRunnerId;
		this.reportMisc = reportMisc;
		this.reportHorsePlaced = reportHorsePlaced;
		this.tempVetNames = tempVetNames;
		this.reportType = reportType;
		this.tempHorsename = tempHorsename;
		this.tempDate = tempDate;
		this.tempTrainer = tempTrainer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "report_id", unique = true, nullable = false)
	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	@Column(name = "report_content", nullable = false, length = 65535)
	public String getReportContent() {
		return this.reportContent;
	}

	public void setReportContent(String reportContent) {
		this.reportContent = reportContent;
	}

	@Column(name = "report_racecard_id")
	public Integer getReportRacecardId() {
		return this.reportRacecardId;
	}

	public void setReportRacecardId(Integer reportRacecardId) {
		this.reportRacecardId = reportRacecardId;
	}

	@Column(name = "report_random_id")
	public Integer getReportRandomId() {
		return this.reportRandomId;
	}

	public void setReportRandomId(Integer reportRandomId) {
		this.reportRandomId = reportRandomId;
	}

	@Column(name = "report_non_runner_id")
	public Integer getReportNonRunnerId() {
		return this.reportNonRunnerId;
	}

	public void setReportNonRunnerId(Integer reportNonRunnerId) {
		this.reportNonRunnerId = reportNonRunnerId;
	}

	@Column(name = "report_misc", length = 65535)
	public String getReportMisc() {
		return this.reportMisc;
	}

	public void setReportMisc(String reportMisc) {
		this.reportMisc = reportMisc;
	}

	@Column(name = "report_horse_placed", length = 20)
	public String getReportHorsePlaced() {
		return this.reportHorsePlaced;
	}

	public void setReportHorsePlaced(String reportHorsePlaced) {
		this.reportHorsePlaced = reportHorsePlaced;
	}

	@Column(name = "temp_vet_names", nullable = false, length = 200)
	public String getTempVetNames() {
		return this.tempVetNames;
	}

	public void setTempVetNames(String tempVetNames) {
		this.tempVetNames = tempVetNames;
	}

	@Column(name = "report_type", nullable = false, length = 22)
	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	@Column(name = "temp_horsename", length = 200)
	public String getTempHorsename() {
		return this.tempHorsename;
	}

	public void setTempHorsename(String tempHorsename) {
		this.tempHorsename = tempHorsename;
	}

	@Column(name = "temp_date", length = 200)
	public String getTempDate() {
		return this.tempDate;
	}

	public void setTempDate(String tempDate) {
		this.tempDate = tempDate;
	}

	@Column(name = "temp_trainer", length = 200)
	public String getTempTrainer() {
		return this.tempTrainer;
	}

	public void setTempTrainer(String tempTrainer) {
		this.tempTrainer = tempTrainer;
	}

}
