// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VetreportMeetingsNotGenerated generated by hbm2java
 */
@Entity
@Table(name = "vetreport_meetings_not_generated", catalog = "vetreports")
public class VetreportMeetingsNotGenerated implements java.io.Serializable {

	private VetreportMeetingsNotGeneratedId id;

	public VetreportMeetingsNotGenerated() {
	}

	public VetreportMeetingsNotGenerated(VetreportMeetingsNotGeneratedId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rowId", column = @Column(name = "row_id", nullable = false)),
			@AttributeOverride(name = "meeting", column = @Column(name = "Meeting", nullable = false, length = 50)),
			@AttributeOverride(name = "dateRan", column = @Column(name = "DateRan", nullable = false, length = 10)) })
	public VetreportMeetingsNotGeneratedId getId() {
		return this.id;
	}

	public void setId(VetreportMeetingsNotGeneratedId id) {
		this.id = id;
	}

}
