// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VetreportReportedbyVets generated by hbm2java
 */
@Entity
@Table(name = "vetreport_reportedby_vets", catalog = "vetreports")
public class VetreportReportedbyVets implements java.io.Serializable {

	private Integer reportedbyId;
	private int reportedbyVetId;
	private int reportedbyReportId;

	public VetreportReportedbyVets() {
	}

	public VetreportReportedbyVets(int reportedbyVetId, int reportedbyReportId) {
		this.reportedbyVetId = reportedbyVetId;
		this.reportedbyReportId = reportedbyReportId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "reportedby_id", unique = true, nullable = false)
	public Integer getReportedbyId() {
		return this.reportedbyId;
	}

	public void setReportedbyId(Integer reportedbyId) {
		this.reportedbyId = reportedbyId;
	}

	@Column(name = "reportedby_vet_id", nullable = false)
	public int getReportedbyVetId() {
		return this.reportedbyVetId;
	}

	public void setReportedbyVetId(int reportedbyVetId) {
		this.reportedbyVetId = reportedbyVetId;
	}

	@Column(name = "reportedby_report_id", nullable = false)
	public int getReportedbyReportId() {
		return this.reportedbyReportId;
	}

	public void setReportedbyReportId(int reportedbyReportId) {
		this.reportedbyReportId = reportedbyReportId;
	}

}
