// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VetreportHorsesId generated by hbm2java
 */
@Embeddable
public class VetreportHorsesId implements java.io.Serializable {

	private String horseId;
	private String horseName;
	private Long horseLastRacecardId;

	public VetreportHorsesId() {
	}

	public VetreportHorsesId(String horseId, String horseName,
			Long horseLastRacecardId) {
		this.horseId = horseId;
		this.horseName = horseName;
		this.horseLastRacecardId = horseLastRacecardId;
	}

	@Column(name = "horse_id", length = 22)
	public String getHorseId() {
		return this.horseId;
	}

	public void setHorseId(String horseId) {
		this.horseId = horseId;
	}

	@Column(name = "horse_name", length = 200)
	public String getHorseName() {
		return this.horseName;
	}

	public void setHorseName(String horseName) {
		this.horseName = horseName;
	}

	@Column(name = "horse_last_racecard_id")
	public Long getHorseLastRacecardId() {
		return this.horseLastRacecardId;
	}

	public void setHorseLastRacecardId(Long horseLastRacecardId) {
		this.horseLastRacecardId = horseLastRacecardId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VetreportHorsesId))
			return false;
		VetreportHorsesId castOther = (VetreportHorsesId) other;

		return ((this.getHorseId() == castOther.getHorseId()) || (this
				.getHorseId() != null && castOther.getHorseId() != null && this
				.getHorseId().equals(castOther.getHorseId())))
				&& ((this.getHorseName() == castOther.getHorseName()) || (this
						.getHorseName() != null
						&& castOther.getHorseName() != null && this
						.getHorseName().equals(castOther.getHorseName())))
				&& ((this.getHorseLastRacecardId() == castOther
						.getHorseLastRacecardId()) || (this
						.getHorseLastRacecardId() != null
						&& castOther.getHorseLastRacecardId() != null && this
						.getHorseLastRacecardId().equals(
								castOther.getHorseLastRacecardId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHorseId() == null ? 0 : this.getHorseId().hashCode());
		result = 37 * result
				+ (getHorseName() == null ? 0 : this.getHorseName().hashCode());
		result = 37
				* result
				+ (getHorseLastRacecardId() == null ? 0 : this
						.getHorseLastRacecardId().hashCode());
		return result;
	}

}
