// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VetReportRandomStableInspectionDetail generated by hbm2java
 */
@Entity
@Table(name = "vet_report_random_stable_inspection_detail", catalog = "vetreports")
public class VetReportRandomStableInspectionDetail implements
		java.io.Serializable {

	private Integer randomId;
	private int randomTrainerId;
	private Integer randomHorseId;
	private Date randomInpsectionDate;
	private String randomNotRanYetHorsename;

	public VetReportRandomStableInspectionDetail() {
	}

	public VetReportRandomStableInspectionDetail(int randomTrainerId,
			Date randomInpsectionDate) {
		this.randomTrainerId = randomTrainerId;
		this.randomInpsectionDate = randomInpsectionDate;
	}

	public VetReportRandomStableInspectionDetail(int randomTrainerId,
			Integer randomHorseId, Date randomInpsectionDate,
			String randomNotRanYetHorsename) {
		this.randomTrainerId = randomTrainerId;
		this.randomHorseId = randomHorseId;
		this.randomInpsectionDate = randomInpsectionDate;
		this.randomNotRanYetHorsename = randomNotRanYetHorsename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "random_id", unique = true, nullable = false)
	public Integer getRandomId() {
		return this.randomId;
	}

	public void setRandomId(Integer randomId) {
		this.randomId = randomId;
	}

	@Column(name = "random_trainer_id", nullable = false)
	public int getRandomTrainerId() {
		return this.randomTrainerId;
	}

	public void setRandomTrainerId(int randomTrainerId) {
		this.randomTrainerId = randomTrainerId;
	}

	@Column(name = "random_horse_id")
	public Integer getRandomHorseId() {
		return this.randomHorseId;
	}

	public void setRandomHorseId(Integer randomHorseId) {
		this.randomHorseId = randomHorseId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "random_inpsection_date", nullable = false, length = 10)
	public Date getRandomInpsectionDate() {
		return this.randomInpsectionDate;
	}

	public void setRandomInpsectionDate(Date randomInpsectionDate) {
		this.randomInpsectionDate = randomInpsectionDate;
	}

	@Column(name = "random_not_ran_yet_horsename", length = 200)
	public String getRandomNotRanYetHorsename() {
		return this.randomNotRanYetHorsename;
	}

	public void setRandomNotRanYetHorsename(String randomNotRanYetHorsename) {
		this.randomNotRanYetHorsename = randomNotRanYetHorsename;
	}

}
