// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VetreportRacecard generated by hbm2java
 */
@Entity
@Table(name = "vetreport_racecard", catalog = "vetreports")
public class VetreportRacecard implements java.io.Serializable {

	private VetreportRacecardId id;

	public VetreportRacecard() {
	}

	public VetreportRacecard(VetreportRacecardId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rowId", column = @Column(name = "row_id", nullable = false)),
			@AttributeOverride(name = "accountNo", column = @Column(name = "Account_No", nullable = false, length = 10)),
			@AttributeOverride(name = "trainerName", column = @Column(name = "Trainer_Name", nullable = false, length = 50)),
			@AttributeOverride(name = "raceNo", column = @Column(name = "Race_No", nullable = false, length = 50)),
			@AttributeOverride(name = "horseName", column = @Column(name = "Horse_Name", nullable = false, length = 50)),
			@AttributeOverride(name = "riderName", column = @Column(name = "Rider_Name", nullable = false, length = 50)),
			@AttributeOverride(name = "owner1", column = @Column(name = "Owner1", nullable = false, length = 50)),
			@AttributeOverride(name = "owner2", column = @Column(name = "Owner2", nullable = false, length = 50)),
			@AttributeOverride(name = "owner3", column = @Column(name = "Owner3", nullable = false, length = 50)),
			@AttributeOverride(name = "owner4", column = @Column(name = "Owner4", nullable = false, length = 50)),
			@AttributeOverride(name = "dateRan", column = @Column(name = "DateRan", nullable = false, length = 10)),
			@AttributeOverride(name = "meeting", column = @Column(name = "Meeting", nullable = false, length = 50)),
			@AttributeOverride(name = "date", column = @Column(name = "Date", nullable = false, length = 19)),
			@AttributeOverride(name = "betFairImported", column = @Column(name = "Bet_Fair_Imported", nullable = false)),
			@AttributeOverride(name = "horseNum", column = @Column(name = "Horse_Num", nullable = false)),
			@AttributeOverride(name = "raceCode", column = @Column(name = "raceCode", length = 10)),
			@AttributeOverride(name = "raceName", column = @Column(name = "raceName", length = 200)),
			@AttributeOverride(name = "jockeyAccNo", column = @Column(name = "jockeyAccNo", length = 200)) })
	public VetreportRacecardId getId() {
		return this.id;
	}

	public void setId(VetreportRacecardId id) {
		this.id = id;
	}

}
