// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VetreportsEnquiriesId generated by hbm2java
 */
@Embeddable
public class VetreportsEnquiriesId implements java.io.Serializable {

	private int enqId;
	private String enqText;
	private String enqMeeting;
	private Date enqDate;
	private String enqEnteredBy;
	private byte enqIsDeleted;
	private String enqRaceCode;
	private String enqRaceName;
	private String enqEnqType;
	private byte enqIsSentToCalendar;
	private byte enqIsUploaded;
	private byte enqShouldHaveDiscip;
	private byte enqIsEmailed;
	private byte enqIsAccepted;
	private byte enqIsTurfclubApproved;

	public VetreportsEnquiriesId() {
	}

	public VetreportsEnquiriesId(int enqId, String enqText, String enqMeeting,
			Date enqDate, String enqEnteredBy, byte enqIsDeleted,
			String enqRaceCode, String enqRaceName, String enqEnqType,
			byte enqIsSentToCalendar, byte enqIsUploaded,
			byte enqShouldHaveDiscip, byte enqIsEmailed, byte enqIsAccepted,
			byte enqIsTurfclubApproved) {
		this.enqId = enqId;
		this.enqText = enqText;
		this.enqMeeting = enqMeeting;
		this.enqDate = enqDate;
		this.enqEnteredBy = enqEnteredBy;
		this.enqIsDeleted = enqIsDeleted;
		this.enqRaceCode = enqRaceCode;
		this.enqRaceName = enqRaceName;
		this.enqEnqType = enqEnqType;
		this.enqIsSentToCalendar = enqIsSentToCalendar;
		this.enqIsUploaded = enqIsUploaded;
		this.enqShouldHaveDiscip = enqShouldHaveDiscip;
		this.enqIsEmailed = enqIsEmailed;
		this.enqIsAccepted = enqIsAccepted;
		this.enqIsTurfclubApproved = enqIsTurfclubApproved;
	}

	@Column(name = "enq_id", nullable = false)
	public int getEnqId() {
		return this.enqId;
	}

	public void setEnqId(int enqId) {
		this.enqId = enqId;
	}

	@Column(name = "enq_text", nullable = false)
	public String getEnqText() {
		return this.enqText;
	}

	public void setEnqText(String enqText) {
		this.enqText = enqText;
	}

	@Column(name = "enq_meeting", nullable = false, length = 200)
	public String getEnqMeeting() {
		return this.enqMeeting;
	}

	public void setEnqMeeting(String enqMeeting) {
		this.enqMeeting = enqMeeting;
	}

	@Column(name = "enq_date", nullable = false, length = 10)
	public Date getEnqDate() {
		return this.enqDate;
	}

	public void setEnqDate(Date enqDate) {
		this.enqDate = enqDate;
	}

	@Column(name = "enq_entered_by", nullable = false, length = 30)
	public String getEnqEnteredBy() {
		return this.enqEnteredBy;
	}

	public void setEnqEnteredBy(String enqEnteredBy) {
		this.enqEnteredBy = enqEnteredBy;
	}

	@Column(name = "enq_is_deleted", nullable = false)
	public byte getEnqIsDeleted() {
		return this.enqIsDeleted;
	}

	public void setEnqIsDeleted(byte enqIsDeleted) {
		this.enqIsDeleted = enqIsDeleted;
	}

	@Column(name = "enq_race_code", nullable = false, length = 20)
	public String getEnqRaceCode() {
		return this.enqRaceCode;
	}

	public void setEnqRaceCode(String enqRaceCode) {
		this.enqRaceCode = enqRaceCode;
	}

	@Column(name = "enq_race_name", nullable = false, length = 200)
	public String getEnqRaceName() {
		return this.enqRaceName;
	}

	public void setEnqRaceName(String enqRaceName) {
		this.enqRaceName = enqRaceName;
	}

	@Column(name = "enq_enq_type", nullable = false, length = 16)
	public String getEnqEnqType() {
		return this.enqEnqType;
	}

	public void setEnqEnqType(String enqEnqType) {
		this.enqEnqType = enqEnqType;
	}

	@Column(name = "enq_is_sent_to_calendar", nullable = false)
	public byte getEnqIsSentToCalendar() {
		return this.enqIsSentToCalendar;
	}

	public void setEnqIsSentToCalendar(byte enqIsSentToCalendar) {
		this.enqIsSentToCalendar = enqIsSentToCalendar;
	}

	@Column(name = "enq_is_uploaded", nullable = false)
	public byte getEnqIsUploaded() {
		return this.enqIsUploaded;
	}

	public void setEnqIsUploaded(byte enqIsUploaded) {
		this.enqIsUploaded = enqIsUploaded;
	}

	@Column(name = "enq_should_have_discip", nullable = false)
	public byte getEnqShouldHaveDiscip() {
		return this.enqShouldHaveDiscip;
	}

	public void setEnqShouldHaveDiscip(byte enqShouldHaveDiscip) {
		this.enqShouldHaveDiscip = enqShouldHaveDiscip;
	}

	@Column(name = "enq_is_emailed", nullable = false)
	public byte getEnqIsEmailed() {
		return this.enqIsEmailed;
	}

	public void setEnqIsEmailed(byte enqIsEmailed) {
		this.enqIsEmailed = enqIsEmailed;
	}

	@Column(name = "enq_is_accepted", nullable = false)
	public byte getEnqIsAccepted() {
		return this.enqIsAccepted;
	}

	public void setEnqIsAccepted(byte enqIsAccepted) {
		this.enqIsAccepted = enqIsAccepted;
	}

	@Column(name = "enq_is_turfclub_approved", nullable = false)
	public byte getEnqIsTurfclubApproved() {
		return this.enqIsTurfclubApproved;
	}

	public void setEnqIsTurfclubApproved(byte enqIsTurfclubApproved) {
		this.enqIsTurfclubApproved = enqIsTurfclubApproved;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VetreportsEnquiriesId))
			return false;
		VetreportsEnquiriesId castOther = (VetreportsEnquiriesId) other;

		return (this.getEnqId() == castOther.getEnqId())
				&& ((this.getEnqText() == castOther.getEnqText()) || (this
						.getEnqText() != null && castOther.getEnqText() != null && this
						.getEnqText().equals(castOther.getEnqText())))
				&& ((this.getEnqMeeting() == castOther.getEnqMeeting()) || (this
						.getEnqMeeting() != null
						&& castOther.getEnqMeeting() != null && this
						.getEnqMeeting().equals(castOther.getEnqMeeting())))
				&& ((this.getEnqDate() == castOther.getEnqDate()) || (this
						.getEnqDate() != null && castOther.getEnqDate() != null && this
						.getEnqDate().equals(castOther.getEnqDate())))
				&& ((this.getEnqEnteredBy() == castOther.getEnqEnteredBy()) || (this
						.getEnqEnteredBy() != null
						&& castOther.getEnqEnteredBy() != null && this
						.getEnqEnteredBy().equals(castOther.getEnqEnteredBy())))
				&& (this.getEnqIsDeleted() == castOther.getEnqIsDeleted())
				&& ((this.getEnqRaceCode() == castOther.getEnqRaceCode()) || (this
						.getEnqRaceCode() != null
						&& castOther.getEnqRaceCode() != null && this
						.getEnqRaceCode().equals(castOther.getEnqRaceCode())))
				&& ((this.getEnqRaceName() == castOther.getEnqRaceName()) || (this
						.getEnqRaceName() != null
						&& castOther.getEnqRaceName() != null && this
						.getEnqRaceName().equals(castOther.getEnqRaceName())))
				&& ((this.getEnqEnqType() == castOther.getEnqEnqType()) || (this
						.getEnqEnqType() != null
						&& castOther.getEnqEnqType() != null && this
						.getEnqEnqType().equals(castOther.getEnqEnqType())))
				&& (this.getEnqIsSentToCalendar() == castOther
						.getEnqIsSentToCalendar())
				&& (this.getEnqIsUploaded() == castOther.getEnqIsUploaded())
				&& (this.getEnqShouldHaveDiscip() == castOther
						.getEnqShouldHaveDiscip())
				&& (this.getEnqIsEmailed() == castOther.getEnqIsEmailed())
				&& (this.getEnqIsAccepted() == castOther.getEnqIsAccepted())
				&& (this.getEnqIsTurfclubApproved() == castOther
						.getEnqIsTurfclubApproved());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEnqId();
		result = 37 * result
				+ (getEnqText() == null ? 0 : this.getEnqText().hashCode());
		result = 37
				* result
				+ (getEnqMeeting() == null ? 0 : this.getEnqMeeting()
						.hashCode());
		result = 37 * result
				+ (getEnqDate() == null ? 0 : this.getEnqDate().hashCode());
		result = 37
				* result
				+ (getEnqEnteredBy() == null ? 0 : this.getEnqEnteredBy()
						.hashCode());
		result = 37 * result + this.getEnqIsDeleted();
		result = 37
				* result
				+ (getEnqRaceCode() == null ? 0 : this.getEnqRaceCode()
						.hashCode());
		result = 37
				* result
				+ (getEnqRaceName() == null ? 0 : this.getEnqRaceName()
						.hashCode());
		result = 37
				* result
				+ (getEnqEnqType() == null ? 0 : this.getEnqEnqType()
						.hashCode());
		result = 37 * result + this.getEnqIsSentToCalendar();
		result = 37 * result + this.getEnqIsUploaded();
		result = 37 * result + this.getEnqShouldHaveDiscip();
		result = 37 * result + this.getEnqIsEmailed();
		result = 37 * result + this.getEnqIsAccepted();
		result = 37 * result + this.getEnqIsTurfclubApproved();
		return result;
	}

}
