// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VetreportMeetingsNotGeneratedId generated by hbm2java
 */
@Embeddable
public class VetreportMeetingsNotGeneratedId implements java.io.Serializable {

	private int rowId;
	private String meeting;
	private Date dateRan;

	public VetreportMeetingsNotGeneratedId() {
	}

	public VetreportMeetingsNotGeneratedId(int rowId, String meeting,
			Date dateRan) {
		this.rowId = rowId;
		this.meeting = meeting;
		this.dateRan = dateRan;
	}

	@Column(name = "row_id", nullable = false)
	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	@Column(name = "Meeting", nullable = false, length = 50)
	public String getMeeting() {
		return this.meeting;
	}

	public void setMeeting(String meeting) {
		this.meeting = meeting;
	}

	@Column(name = "DateRan", nullable = false, length = 10)
	public Date getDateRan() {
		return this.dateRan;
	}

	public void setDateRan(Date dateRan) {
		this.dateRan = dateRan;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VetreportMeetingsNotGeneratedId))
			return false;
		VetreportMeetingsNotGeneratedId castOther = (VetreportMeetingsNotGeneratedId) other;

		return (this.getRowId() == castOther.getRowId())
				&& ((this.getMeeting() == castOther.getMeeting()) || (this
						.getMeeting() != null && castOther.getMeeting() != null && this
						.getMeeting().equals(castOther.getMeeting())))
				&& ((this.getDateRan() == castOther.getDateRan()) || (this
						.getDateRan() != null && castOther.getDateRan() != null && this
						.getDateRan().equals(castOther.getDateRan())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRowId();
		result = 37 * result
				+ (getMeeting() == null ? 0 : this.getMeeting().hashCode());
		result = 37 * result
				+ (getDateRan() == null ? 0 : this.getDateRan().hashCode());
		return result;
	}

}
