// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VetreportNonrunnerDetail generated by hbm2java
 */
@Entity
@Table(name = "vetreport_nonrunner_detail", catalog = "vetreports")
public class VetreportNonrunnerDetail implements java.io.Serializable {

	private Integer nonrunId;
	private boolean nonrunFine;
	private boolean nonrunRefunded;
	private boolean nonrunLate;

	public VetreportNonrunnerDetail() {
	}

	public VetreportNonrunnerDetail(boolean nonrunFine, boolean nonrunRefunded,
			boolean nonrunLate) {
		this.nonrunFine = nonrunFine;
		this.nonrunRefunded = nonrunRefunded;
		this.nonrunLate = nonrunLate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nonrun_id", unique = true, nullable = false)
	public Integer getNonrunId() {
		return this.nonrunId;
	}

	public void setNonrunId(Integer nonrunId) {
		this.nonrunId = nonrunId;
	}

	@Column(name = "nonrun_fine", nullable = false)
	public boolean isNonrunFine() {
		return this.nonrunFine;
	}

	public void setNonrunFine(boolean nonrunFine) {
		this.nonrunFine = nonrunFine;
	}

	@Column(name = "nonrun_refunded", nullable = false)
	public boolean isNonrunRefunded() {
		return this.nonrunRefunded;
	}

	public void setNonrunRefunded(boolean nonrunRefunded) {
		this.nonrunRefunded = nonrunRefunded;
	}

	@Column(name = "nonrun_late", nullable = false)
	public boolean isNonrunLate() {
		return this.nonrunLate;
	}

	public void setNonrunLate(boolean nonrunLate) {
		this.nonrunLate = nonrunLate;
	}

}
