// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VetreportHorses generated by hbm2java
 */
@Entity
@Table(name = "vetreport_horses", catalog = "vetreports")
public class VetreportHorses implements java.io.Serializable {

	private VetreportHorsesId id;

	public VetreportHorses() {
	}

	public VetreportHorses(VetreportHorsesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "horseId", column = @Column(name = "horse_id", length = 22)),
			@AttributeOverride(name = "horseName", column = @Column(name = "horse_name", length = 200)),
			@AttributeOverride(name = "horseLastRacecardId", column = @Column(name = "horse_last_racecard_id")) })
	public VetreportHorsesId getId() {
		return this.id;
	}

	public void setId(VetreportHorsesId id) {
		this.id = id;
	}

}
