// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VetreportHorsesNoForm generated by hbm2java
 */
@Entity
@Table(name = "vetreport_horses_no_form", catalog = "vetreports")
public class VetreportHorsesNoForm implements java.io.Serializable {

	private VetreportHorsesNoFormId id;

	public VetreportHorsesNoForm() {
	}

	public VetreportHorsesNoForm(VetreportHorsesNoFormId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rowId", column = @Column(name = "row_id", nullable = false)),
			@AttributeOverride(name = "horseName", column = @Column(name = "Horse_Name", nullable = false, length = 50)) })
	public VetreportHorsesNoFormId getId() {
		return this.id;
	}

	public void setId(VetreportHorsesNoFormId id) {
		this.id = id;
	}

}
