// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VetreportAlertTrainers generated by hbm2java
 */
@Entity
@Table(name = "vetreport_alert_trainers", catalog = "vetreports")
public class VetreportAlertTrainers implements java.io.Serializable {

	private Integer trainerAlertId;
	private int trainerAlertTrainerId;

	public VetreportAlertTrainers() {
	}

	public VetreportAlertTrainers(int trainerAlertTrainerId) {
		this.trainerAlertTrainerId = trainerAlertTrainerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "trainer_alert_id", unique = true, nullable = false)
	public Integer getTrainerAlertId() {
		return this.trainerAlertId;
	}

	public void setTrainerAlertId(Integer trainerAlertId) {
		this.trainerAlertId = trainerAlertId;
	}

	@Column(name = "trainer_alert_trainer_id", nullable = false)
	public int getTrainerAlertTrainerId() {
		return this.trainerAlertTrainerId;
	}

	public void setTrainerAlertTrainerId(int trainerAlertTrainerId) {
		this.trainerAlertTrainerId = trainerAlertTrainerId;
	}

}
