// default package
// Generated 20-Feb-2015 09:56:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VetreportTrainersId generated by hbm2java
 */
@Embeddable
public class VetreportTrainersId implements java.io.Serializable {

	private int trainerId;
	private String trainerName;

	public VetreportTrainersId() {
	}

	public VetreportTrainersId(int trainerId, String trainerName) {
		this.trainerId = trainerId;
		this.trainerName = trainerName;
	}

	@Column(name = "trainer_id", nullable = false)
	public int getTrainerId() {
		return this.trainerId;
	}

	public void setTrainerId(int trainerId) {
		this.trainerId = trainerId;
	}

	@Column(name = "trainer_name", nullable = false, length = 200)
	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VetreportTrainersId))
			return false;
		VetreportTrainersId castOther = (VetreportTrainersId) other;

		return (this.getTrainerId() == castOther.getTrainerId())
				&& ((this.getTrainerName() == castOther.getTrainerName()) || (this
						.getTrainerName() != null
						&& castOther.getTrainerName() != null && this
						.getTrainerName().equals(castOther.getTrainerName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTrainerId();
		result = 37
				* result
				+ (getTrainerName() == null ? 0 : this.getTrainerName()
						.hashCode());
		return result;
	}

}
