package ie.turfclub.reporting.model.vetreports;
// default package
// Generated 19-Dec-2014 11:30:23 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VetreportHorsesNoFormId generated by hbm2java
 */
@Entity
@Table(name = "vetreport_horses_no_form", catalog = "vetreports")
public class VetreportHorsesNoForm implements java.io.Serializable {

	private String horseName;
	private int rowId;


	public VetreportHorsesNoForm() {
	}

	public VetreportHorsesNoForm(String horseName, int rowId) {
		this.horseName = horseName;
		this.rowId = rowId;

	}



	
	@Column(name = "Horse_Name", nullable = false, length = 50)
	public String getHorseName() {
		return this.horseName;
	}

	public void setHorseName(String horseName) {
		this.horseName = horseName;
	}

	@Id
	@Column(name = "row_id", nullable = false)
	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}





}
