package ie.turfclub.reporting.model.vetreports;

// default package
// Generated 19-Dec-2014 11:19:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VetreportHorseForm generated by hbm2java
 */
@Entity
@Table(name = "vetreport_horse_form", catalog = "vetreports")
public class VetreportHorseForm implements java.io.Serializable {

	private Integer formId;
	private String formHorse;
	private Date formDate;
	private String formConditions;
	private String formRace;
	private String formResult;
	private Integer formRcId;
	private String formTrack;

	public VetreportHorseForm() {
	}

	public VetreportHorseForm(String formHorse, Date formDate,
			String formConditions, String formRace, String formResult) {
		this.formHorse = formHorse;
		this.formDate = formDate;
		this.formConditions = formConditions;
		this.formRace = formRace;
		this.formResult = formResult;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "form_id", unique = true, nullable = false)
	public Integer getFormId() {
		return this.formId;
	}

	public void setFormId(Integer formId) {
		this.formId = formId;
	}

	@Column(name = "form_horse", nullable = false, length = 200)
	public String getFormHorse() {
		return this.formHorse;
	}

	public void setFormHorse(String formHorse) {
		this.formHorse = formHorse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "form_date", nullable = false, length = 10)
	public Date getFormDate() {
		return this.formDate;
	}

	public void setFormDate(Date formDate) {
		this.formDate = formDate;
	}

	@Column(name = "form_conditions", nullable = false, length = 50)
	public String getFormConditions() {
		return this.formConditions;
	}

	public void setFormConditions(String formConditions) {
		this.formConditions = formConditions;
	}

	@Column(name = "form_race", nullable = false, length = 50)
	public String getFormRace() {
		return this.formRace;
	}

	public void setFormRace(String formRace) {
		this.formRace = formRace;
	}

	@Column(name = "form_result", nullable = false)
	public String getFormResult() {
		return this.formResult;
	}

	public void setFormResult(String formResult) {
		this.formResult = formResult;
	}

	@Column(name = "form_rc_id", nullable = false, length = 20)
	public Integer getFormRcId() {
		return formRcId;
	}

	public void setFormRcId(Integer formRcId) {
		this.formRcId = formRcId;
	}
	@Column(name = "form_track", nullable = false)
	public String getFormTrack() {
		return formTrack;
	}

	public void setFormTrack(String formTrack) {
		this.formTrack = formTrack;
	}

	
	
	

}
