package ie.turfclub.reporting.model.pointToPoint;
// default package
// Generated 02-Oct-2014 15:38:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.Id;

import javax.persistence.Table;


/**
 * P2pHuntercertsSales generated by hbm2java
 */
@Entity
@Table(name = "p2p_huntercerts_sales", catalog = "p2p")
public class HuntercertsSales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String salesOrderId;

	private String salesAmount;
	private String salesPayee;

	public HuntercertsSales() {
	}

	public HuntercertsSales(
			String salesAmount, String salesPayee) {
		this.salesAmount = salesAmount;
		this.salesPayee = salesPayee;
	}

	
	@Id
	@Column(name = "sales_order_id", unique = true, nullable = false, length = 12)
	public String getSalesOrderId() {
		return this.salesOrderId;
	}

	public void setSalesOrderId(String salesOrderId) {
		this.salesOrderId = salesOrderId;
	}



	@Column(name = "sales_amount", nullable = false, length = 10)
	public String getSalesAmount() {
		return this.salesAmount;
	}

	public void setSalesAmount(String salesAmount) {
		this.salesAmount = salesAmount;
	}

	@Column(name = "sales_payee", nullable = false, length = 200)
	public String getSalesPayee() {
		return this.salesPayee;
	}

	public void setSalesPayee(String salesPayee) {
		this.salesPayee = salesPayee;
	}

}
