package ie.turfclub.reporting.model.pointToPoint;
// default package
// Generated 02-Oct-2014 15:38:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * P2pHunts generated by hbm2java
 */
@Entity
@Table(name = "p2p_hunts", catalog = "p2p")
public class Hunts implements java.io.Serializable {

	private int huntId;
	private String huntName;
	private int huntPrice;


	public Hunts() {
	}

	public Hunts(int huntId, String huntName, int huntPrice) {
		this.huntId = huntId;
		this.huntName = huntName;
		this.huntPrice = huntPrice;
	}

	

	@Id
	@Column(name = "hunt_id", unique = true, nullable = false)
	public int getHuntId() {
		return this.huntId;
	}

	public void setHuntId(int huntId) {
		this.huntId = huntId;
	}

	@Column(name = "hunt_name", nullable = false, length = 200)
	public String getHuntName() {
		return this.huntName;
	}

	public void setHuntName(String huntName) {
		this.huntName = huntName;
	}

	@Column(name = "hunt_price", nullable = false)
	public int getHuntPrice() {
		return this.huntPrice;
	}

	public void setHuntPrice(int huntPrice) {
		this.huntPrice = huntPrice;
	}


}
